### ISSUE TITLE
[Quest/G6PD] - Bug : App crashing on device running Android 6.0.1

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1170]
**Description** 
The client reports that the app crashed while trying to run on their device. Details are shared on the screenshot below 

**Details** 
Check the android version and build from the screenshot share below 

**Screenshot**
<img src="https://user-images.githubusercontent.com/4540684/160072720-057f1a93-0ca3-45f2-9cb9-9c5cee3dee2b.png" width="400" height="600" />

**Desired fix** 
1. Replicate the bug using the shares detail above 
2. Create a fix for the Android Version currently run on the test device

**Comment by f-odhiambo** [comment]
NB. Could be related to a similar issue https://github.com/opensrp/fhircore/issues/1122

**Comment by f-odhiambo** [comment]
We may also need to revise the supported Android version to 8 and not as stipulated here: The SDK supports Android 21 (lollipop) and above. The SDK supports Android 21 (lollipop) and above
NB/ Lower Android version requires more additional code support for feature and security  patches

**Comment by pld** [comment]
Do we have a video showing the crash and any debugging info related to it?

**Comment by f-odhiambo** [comment]
> Do we have a video showing the crash and any debugging info related to it?
No further details shared

**Comment by ellykits** [comment]
I think this could be related to using date APIs that are targeting Android API level 26 and above.

**Comment by ellykits** [comment]
We use the new APIs for instance to calculate age. We need to refactor the implementation to handle apps with api level below 26.

**Comment by maimoonak** [comment]
For G6PD app, on Pixel 2, API 23 i.e. Marshmallow, 6.0
- App login, sync, registration, profile, details works fine
- Shift+Aplha does not work (could be emulator issue)
- Date control keeps popping up even when date is selected in birthdate. We have to use Cancel button to hide calendar
- In Test Results form , java.lang.NoSuchMethodError: No virtual method getParameterCount()I in class Ljava/lang/reflect/Method; or its super classes, in CQL, 
```
at org.opencds.cqf.cql.engine.data.SystemDataProvider.getWriteAccessor(SystemDataProvider.java:75)
        at org.opencds.cqf.cql.engine.data.SystemDataProvider.setValue(SystemDataProvider.java:117)
        at org.opencds.cqf.cql.engine.execution.Context.setValue(Context.java:857)
        at org.opencds.cqf.cql.engine.elm.execution.InstanceEvaluator.internalEvaluate(InstanceEvaluator.java:12)
        at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18)...................
        at org.opencds.cqf.cql.engine.elm.execution.QueryEvaluator.evaluateWhere(QueryEvaluator.java:75).....................
        at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:18)
        at org.opencds.cqf.cql.engine.execution.CqlEngine.evaluateExpressions(CqlEngine.java:186)
        at org.opencds.cqf.cql.engine.execution.CqlEngine.evaluate(CqlEngine.java:164)
        at org.opencds.cqf.cql.evaluator.CqlEvaluator.evaluate(CqlEvaluator.java:89)
        at org.opencds.cqf.cql.evaluator.library.LibraryEvaluator.evaluate(LibraryEvaluator.java:47)
        at org.smartregister.fhircore.engine.cql.LibraryEvaluator.runCqlLibrary(LibraryEvaluator.kt:253)
        at org.smartregister.fhircore.engine.cql.LibraryEvaluator$runCqlLibrary$1.invokeSuspend(LibraryEvaluator.kt)
```
- Post data entry Sync failing for all entities with 'exception=retrofit2.HttpException: HTTP 400' (I m not able to debug database for some reason in my IDE)

So main issue for G6PD is CQL Library relying on java 8+. We can try downgrading but that can pose other issues like (Now function for datetime not supported etc). The sync thing most probably could be due to SDK update which we might have not handled properly (I need to confirm this).

**Comment by f-odhiambo** [comment]
I can report this back to the client as feedback. I think we can check on the ANC pieces using CQL. From what I see only measure reporting may be affected as it's the only piece I see working with CQL for now. I think we should work on this post as a Scheduling and Tasking stop-gap. . I am sure will need CQL for that piece too
CC @dubdabasoduba
