### ISSUE TITLE
[Quest/eCBIS] - Remove from ANC Register not working 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1442]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy A2 emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

<img src="https://user-images.githubusercontent.com/4540684/179399590-7886471c-4e26-4875-94aa-2b7ce0db4d4b.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/179399595-eac3b9d0-a42b-4fd1-b82f-b38327b68aa6.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/179399598-30c60c53-6b7a-4aef-b9f4-3bd107640a55.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/179399599-e227fabf-c480-4f27-81b1-011ac6762c47.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/4540684/179399601-3ea8796c-f668-4141-b015-bb7f21bf9c5f.png" width="200" height="400" />

**Comment by f-odhiambo** [comment]
Do we need to remove related FHIR Resource artefacts e.g. Pregnancy Condition, CarePlan, etc.? CC @dubdabasoduba @AnnieMungai

**Comment by f-odhiambo** [comment]
Logcat 
`2022-07-20 10:48:18.420 5265-5265/org.smartregister.fhircore.ecbis E/RemoveFamilyMemberViewModel$remove: java.lang.IllegalStateException: Patient already deleted
        at org.smartregister.fhircore.engine.data.local.register.dao.FamilyRegisterDao.removeFamilyMember(FamilyRegisterDao.kt:228)
        at org.smartregister.fhircore.engine.data.local.register.dao.FamilyRegisterDao$removeFamilyMember$1.invokeSuspend(Unknown Source:21)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`
