### ISSUE TITLE
App force closes on saving a questionnaire

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1717]
**Describe the bug**
- After saving the ANC follow up form on the eCBIS app. The app force closes. 

**To Reproduce**
1. Go to a family and find a female patient who is registered as pregnant. 
2. On the eCBIS preview app user the **Krizz Daniel family** and check the patient **Mama Daniel**
3. Go the to patients profile. 
4. Fill in the ANC Follow up task
5. The apps force closes on save

**Expected behavior**
- [ ] The app should save without a force close

**Additional context**
```cmd
Process: org.smartregister.fhircore.ecbis, PID: 9422
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.smartregister.fhircore.ecbis/org.smartregister.fhircore.quest.ui.main.AppMainActivity}: java.util.NoSuchElementException: Key navigation is missing in the map.
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2945)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3092)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1815)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6874)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                                                                                                    Caused by: java.util.NoSuchElementException: Key navigation is missing in the map.
                                                                                                    	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
                                                                                                    	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:346)
                                                                                                    	at org.smartregister.fhircore.quest.ui.main.AppMainViewModel$navigationConfiguration$2.invoke(AppMainViewModel.kt:313)
                                                                                                    	at org.smartregister.fhircore.quest.ui.main.AppMainViewModel$navigationConfiguration$2.invoke(AppMainViewModel.kt:102)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at org.smartregister.fhircore.quest.ui.main.AppMainViewModel.getNavigationConfiguration(AppMainViewModel.kt:102)
                                                                                                    	at org.smartregister.fhircore.quest.ui.main.AppMainActivity.onCreate(AppMainActivity.kt:74)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8606)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8597)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1274)
```

**Comment by Gental-Giant** [comment]
This is also affecting the restock form. The app crashes when you try to save the form

**Steps to repro:**
1. Navigate to the stock register
2. Click on "restock" and fill out the form
3. Once done, click on save

**Comment by dubdabasoduba** [comment]
> This is also affecting the restock form. The app crashes when you try to save the form
> 
> **Steps to repro:**
> 
> 1. Navigate to the stock register
> 2. Click on "restock" and fill out the form
> 3. Once done, click on save

@Gental-Giant Do you have to fill out all the questions?

**Comment by AnnieMungai** [comment]
This is affecting all forms that are attached to a task @dubdabasoduba @ellykits.

**Comment by AnnieMungai** [comment]
Looks good! 

Restock form can load and save (no extractions). 
Follow-up visit forms on tasks can now save.
