### ISSUE TITLE
Questionnaires crash on Edit mode. 

### ISSUE THREAD

**Issue by AbdulWahabMemon** [opensrp/fhircore#1996]
**Application is crash while editing patient profile**
Patient registration questionnaire getting mismatched with questionnaire-response items, thus its crashing with index out of bound exceptions

here are the logs:
FATAL EXCEPTION: DefaultDispatcher-worker-1
                                         Process: org.smartregister.fhircore.echis, PID: 8359
                                         java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
                                         	at java.util.ArrayList.get(ArrayList.java:437)
                                         	at org.smartregister.fhircore.engine.util.extension.ResourceExtensionKt.generateMissingItems(ResourceExtension.kt:165)
                                         	at org.smartregister.fhircore.engine.util.extension.ResourceExtensionKt.generateMissingItems(ResourceExtension.kt:167)
                                         	at org.smartregister.fhircore.engine.util.extension.ResourceExtensionKt.generateMissingItems(ResourceExtension.kt:158)
                                         	at org.smartregister.fhircore.quest.ui.questionnaire.QuestionnaireActivity.renderFragment(QuestionnaireActivity.kt:198)

**To Reproduce**
1. Go to patient profile
2. Click on registration info, that will launch registration questionnaire in Edit
3. App crashes

**Screenshots**
<img width="1128" alt="Screen Shot 2023-02-01 at 4 16 28 PM" src="https://user-images.githubusercontent.com/66945489/216080360-97c40edd-902c-4720-a9aa-ebbee8461646.png">

**Additional context**
As patient registration is having Age item if DOB is unknown, when its submitted the questionnaire-response there will be either age or DOB in items, but on editing the patient registration these both item values are expected  ...

**Comment by NaveenZehra11** [comment]
issue resolved


https://user-images.githubusercontent.com/90256461/218742764-5a9f6813-5c5e-456a-bfc9-708a3d2ffea4.mp4


Crash issue is fixed but the opensrpId and National Id are not auto filled in the edit able mode

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.9-ecbis-rc4

System Detail : Andorid 9
OS verions : 9.0.6
Storage : 6GB RAM + 64 GB ROM

cc @AnnieMungai
