### ISSUE TITLE
[P2P Sync] Initial P2P sync data transfer is slow

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2051]
**Describe the bug**
- We use the P2P module to transfer data from one device to another in offline mode. The initial transfer fetches all the data from the sending device to the receiving device.  This is to create a baseline for the subsequent transfers. 
- We might have a lot of data in the sending device which means the transfer might take longer. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the latest [eCBIS](https://github.com/opensrp/fhircore/releases/tag/v0.1.9-ecbis-rc4) release on 2 devices.
2. Use one device as the CHA (sender) and the other as CHSS (receiver)
3. After login and syncing on both devices, create a family on the sender device. 
4. Forget all the wifi networks on both devices. 
5. Start the P2P transfer.  
6. You will notice the transfer takes a while

**Expected behaviour**
- [ ] The initial transfer should pick all the data from the sender to the receiver device.  This should however happen in a fairly fast setting.  
     - [ ] We can have a benchmark of 5 - 10 mins (this might be very ambitious) but we can start by reducing it from the current 40 mins. 
- [ ] When the sync takes long it ends up force closing one of the apps mostly the sender device. 

**Acceptance criteria**
- [ ] Reduce the sync time from 40mins to at least 5 - 10mins depending on the data.

**Comment by dubdabasoduba** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.ecbis, PID: 15954
    java.lang.RuntimeException: Unable to pause activity {org.smartregister.fhircore.ecbis/org.smartregister.p2p.search.ui.P2PDeviceSearchActivity}: java.lang.IllegalArgumentException: Channel needs to be initialized
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5260)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5211)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5162)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:247)
        at android.app.ActivityThread.main(ActivityThread.java:8656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalArgumentException: Channel needs to be initialized
        at android.net.wifi.p2p.WifiP2pManager.checkChannel(WifiP2pManager.java:1407)
        at android.net.wifi.p2p.WifiP2pManager.stopPeerDiscovery(WifiP2pManager.java:1572)
        at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy.stopSearchingDevices(WifiDirectDataSharingStrategy.kt:1025)
        at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy.closeSocketAndStreams(WifiDirectDataSharingStrategy.kt:1047)
        at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy.onPause(WifiDirectDataSharingStrategy.kt:824)
        at org.smartregister.p2p.search.ui.P2PDeviceSearchActivity.onPause(P2PDeviceSearchActivity.kt:360)
        at android.app.Activity.performPause(Activity.java:8400)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5250)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5211) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5162) 
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:247) 
        at android.app.ActivityThread.main(ActivityThread.java:8656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

Here is the error I get when P2P eventually breaks.

**Comment by dubdabasoduba** [comment]
Closing this since the PRs were merged. We can open other bug issues if need be.

**Comment by dubdabasoduba** [comment]
https://github.com/opensrp/fhircore/pull/2062 Linking this PR to the issue.

**Comment by AnnieMungai** [comment]
Closing this at the moment until we agree on the improved transfer speeds - this is an improvement of from the previous releases.
