### ISSUE TITLE
Initial sync not completing to 100% gets to 28% and toast message sync complete is shown

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2916]
**Describe the bug**
Initial sync gets to 28% and after that the sync modal disappears and the HH register loads and the **sync complete** toast message is shown below
**To Reproduce**
1. Install the gateway apk (Immunizer, cadre or Bidan app)
2. Launch the application
3. Enter the app id for the app you installed. 
4. Enter username and password
5. Enter a pin
6. Sync begins but  gets to 28%.(See screen recording attached)

**Expected behavior**
Sync should get to 100%

**Screenshots**

https://github.com/ona-health/sid-dto-fhir-resources/assets/73172427/79c44c49-e6c3-4a2a-a1c2-c3d6a83f4721

**Comment by dubdabasoduba** [comment]
@SebaMutuku please add the comment on what you are getting on the server. I think this is a server-side issue

**Comment by SebaMutuku** [comment]
@dubdabasoduba below are the errors thrown by the app when trying to sync
And this error

```
java.net.UnknownServiceException: CLEARTEXT communication to gateway-sid.stage.opensrp.id not permitted by network security policy
                                                                                                    	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:188)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at io.sentry.android.okhttp.SentryOkHttpInterceptor.intercept(SentryOkHttpInterceptor.kt:91)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.google.android.fhir.sync.remote.RetrofitHttpService$Builder.build$lambda$5$lambda$4$lambda$3(RetrofitHttpService.kt:105)
                                                                                                    	at com.google.android.fhir.sync.remote.RetrofitHttpService$Builder.$r8$lambda$wfjHqGwGaaRMLHL4G_NyQ4GUeTU(Unknown Source:0)
                                                                                                    	at com.google.android.fhir.sync.remote.RetrofitHttpService$Builder$$ExternalSyntheticLambda0.intercept(Unknown Source:2)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.google.android.fhir.sync.remote.GzipUploadInterceptor.intercept(GzipUploadInterceptor.kt:35)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    	Suppressed: java.net.UnknownServiceException: CLEARTEXT communication to gateway-sid.stage.opensrp.id not permitted by network security policy
                                                                                                    		... 28 more
                                                                                                    	Suppressed: java.net.UnknownServiceException: CLEARTEXT communication to gateway-sid.stage.opensrp.id not permitted by network security policy
                                                                                                    		... 28 more
                                                                                                    	Suppressed: java.net.UnknownServiceException: CLEARTEXT communication to gateway-sid.stage.opensrp.id not permitted by network security policy
                                                                                                    		... 28 more
```


And 
```
retrofit2.HttpException: HTTP 403 
                                                                                                    	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
                                                                                                    	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
```

**Comment by SebaMutuku** [comment]
After further investigation, I realized there's an `http` call made to the server when syncing data

**Comment by dubdabasoduba** [comment]
@bennsimon We need to test out the apache address strategies on the latest gateway deployments.

**Comment by maimoonak** [comment]
Here are some of the errors found in logs for some resources. The sync is completed partially

```
GET https://*****-sid.*******/fhir/Immunization?patient.organization=**********************&_count=250&_sort=_lastUpdated&_summary=count
17:36:08.991  D  <-- 403 https://****-sid.****/fhir/Immunization?patient.organization=*****b&_count=250&_sort=_lastUpdated&_summary=count (228ms, unknown-length body)
17:36:08.999  E  retrofit2.HttpException: HTTP 403 
                 	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
                 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
                 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:923)
```

For Encounter, Observation and QuestionnaireResponse

```
17:36:21.549  D  --> GET http://************/fhir?_getpages=2268**********af2d&_getpagesoffset=250&_count=250&_pretty=true&_bundletype=searchset
17:36:21.584  D  <-- HTTP FAILED: java.net.UnknownServiceException: CLEARTEXT communication to gateway-sid.stage.opensrp.id not permitted by network security policy
17:36:21.589  E  java.net.UnknownServiceException: CLEARTEXT communication to ************ not permitted by network security policy
                 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:188)
                 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
                 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
                 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
                 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
                 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
```
