### ISSUE TITLE
App Not Responding message on various actions 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#2918]
Devices used:
Samsung A12 `android 11. `
G60 blu `android 9`

Apk: https://github.com/opensrp/fhircore/releases/tag/canary-23-11-2023 (Gateway)

**Describe the bug**
We are experiencing crashes while performing various actions on all the apps (bidan, cadre, sidEir). Some of the actions include:
- install the app and launch the app and see it crashes. 
- install and sync and open a HH and observe it Crashes.
- App crashing during sync.

**To Reproduce**

- Install the app.
- perform various actions on the app
- observe the crashes while performing various actions.

Logs:
`FATAL EXCEPTION: main
                                                                                                    Process: org.smartregister.opensrp.sidBunda, PID: 17555
                                                                                                    java.lang.RuntimeException: Unable to create application org.smartregister.fhircore.quest.QuestApplication: javax.crypto.AEADBadTagException
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5998)
                                                                                                    	at android.app.ActivityThread.access$1100(ActivityThread.java:203)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6874)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                                                                                                    Caused by: javax.crypto.AEADBadTagException
                                                                                                    	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
                                                                                                    	at javax.crypto.Cipher.doFinal(Cipher.java:2113)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:118)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:101)
                                                                                                    	at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:919)
                                                                                                    	at com.google.crypto.tink.KeysetHandle.readWithAssociatedData(KeysetHandle.java:804)
                                                                                                    	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:785)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readMasterkeyDecryptAndParseKeyset(AndroidKeysetManager.java:381)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:297)
                                                                                                    	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:169)
                                                                                                    	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:130)
                                                                                                    	at org.smartregister.fhircore.engine.util.SecureSharedPreference.<init>(SecureSharedPreference.kt:36)
                                                                                                    	at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerQuestApplication_HiltComponents_SingletonC.java:1150)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerQuestApplication_HiltComponents_SingletonC.java:1147)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerQuestApplication_HiltComponents_SingletonC.java:1144)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerQuestApplication_HiltComponents_SingletonC.java:1248)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$SingletonCImpl.injectQuestApplication2(DaggerQuestApplication_HiltComponents_SingletonC.java:1107)
                                                                                                    	at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$SingletonCImpl.injectQuestApplication(DaggerQuestApplication_HiltComponents_SingletonC.java:1101)
                                                                                                    	at org.smartregister.fhircore.quest.Hilt_QuestApplication.hiltInternalInject(Hilt_QuestApplication.java:52)
                                                                                                    	at org.smartregister.fhircore.quest.Hilt_QuestApplication.onCreate(Hilt_QuestApplication.java:43)
                                                                                                    	at org.smartregister.fhircore.quest.QuestApplication.onCreate(QuestApplication.kt:52)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5992)
                                                                                                    	at android.app.ActivityThread.access$1100(ActivityThread.java:203)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6874)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                                                                                                    Caused by: android.security.KeyStoreException: Signature/MAC verification failed
                                                                                                    	at android.security.KeyStore.getKeyStoreException(KeyStore.java:850)
---------------------------- PROCESS STARTED (17555) for package org.smartregister.opensrp.sidBunda ----------------------------`

![image](https://github.com/ona-health/sid-dto-fhir-resources/assets/84722169/080bc979-9128-4dd8-805d-5a1aa798a361)

**Expected behavior**
We should not have app crashes on the app.

**Comment by f-odhiambo** [comment]
Moved this ticket here 
CC @MargaretNjenga @madrinekariuki @Mstjamush

**Comment by dubdabasoduba** [comment]
@f-odhiambo does the error log added here get thrown every time there is an ANR?

**Comment by f-odhiambo** [comment]
> @f-odhiambo does the error log added here get thrown every time there is an ANR?

No.  I also get this on a higher android version 13 and above will add more logs
