### ISSUE TITLE
Log in failure on opensrp-0.2.5 and data-migration-prod-apps branches

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2946]
**Describe the bug**
On `opensrp-0.2.5` the application does not progress to the log in page after the `Application ID` has been entered.
On `data-migration-prod-apps` the user is able to navigate to the login page after entering the `Application ID` . Log in fails with `login error:  Failed to fetch user details` error. 

This has only been tested on the demo server using WDF credentials. We may need to test with other flavors to verify whether this is a widespread issue

The following logs are displayed 

```
2024-01-04 10:15:17.517  9290-10067 okhttp.OkHttpClient     org.smartregister.opensrp.wdf        I  <-- 404 https://gateway-fhir.demo.smartregister.org/fhir/practitioner-details?keycloak-uuid=6962e975-00bf-44b4-9cb0-b2b564f5b58a (2818ms, unknown-length body)
2024-01-04 10:15:17.520  9290-9332  LoginViewModel$login    org.smartregister.opensrp.wdf        E  retrofit2.HttpException: HTTP 404 
                                                                                                    	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
                                                                                                    	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E  {
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E    "resourceType": "OperationOutcome",
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E    "text": {
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E      "status": "generated",
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E      "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>HAPI-0302: Unknown resource type 'practitioner-details' - Server knows how to handle: [Account, ActivityDefinition, AdverseEvent, AllergyIntolerance, Appointment, AppointmentResponse, AuditEvent, Basic, Binary, BiologicallyDerivedProduct, BodyStructure, Bundle, CapabilityStatement, CarePlan, CareTeam, CatalogEntry, ChargeItem, ChargeItemDefinition, Claim, ClaimResponse, ClinicalImpression, CodeSystem, Communication, CommunicationRequest, CompartmentDefinition, Composition, ConceptMap, Condition, Consent, Contract, Coverage, CoverageEligibilityRequest, CoverageEligibilityResponse, DetectedIssue, Device, DeviceDefinition, DeviceMetric, DeviceRequest, DeviceUseStatement, DiagnosticReport, DocumentManifest, DocumentReference, EffectEvidenceSynthesis, Encounter, Endpoint, EnrollmentRequest, EnrollmentResponse, EpisodeOfCare, EventDefinition, Evidence, EvidenceVariable, ExampleScenario, ExplanationOfBenefit, FamilyMemberHistory, Flag, Goal, GraphDefinition, Group, GuidanceResponse, HealthcareService, ImagingStudy, Immunization, ImmunizationEvaluation, ImmunizationRecommendation, ImplementationGuide, InsurancePlan, Invoice, Library, Linkage, ListResource, Location, Measure, MeasureReport, Media, Medication, MedicationAdministration, MedicationDispense, MedicationKnowledge, MedicationRequest, MedicationStatement, MedicinalProduct, MedicinalProductAuthorization, MedicinalProductContraindication, MedicinalProductIndication, MedicinalProductIngredient, MedicinalProductInteraction, MedicinalProductManufactured, MedicinalProductPackaged, MedicinalProductPharmaceutical, MedicinalProductUndesirableEffect, MessageDefinition, MessageHeader, MolecularSequence, NamingSystem, NutritionOrder, Observation, ObservationDefinition, OperationDefinition, OperationOutcome, Organization, OrganizationAffiliation, Parameters, Patient, PaymentNotice, PaymentReconciliation, Person, PlanDefinition, Practitioner, PractitionerRole, Procedure, Provenance, Questionnaire, QuestionnaireResponse, RelatedPerson, RequestGroup, ResearchDefinition, ResearchElementDefinition, ResearchStudy, ResearchSubject, RiskAssessment, RiskEvidenceSynthesis, Schedule, SearchParameter, ServiceRequest, Slot, Specimen, SpecimenDefinition, StructureDefinition, StructureMap, Subscription, Substance, SubstanceNucleicAcid, SubstancePolymer, SubstanceProtein, SubstanceReferenceInformation, SubstanceSourceMaterial, SubstanceSpecification, SupplyDelivery, SupplyRequest, Task, TerminologyCapabilities, TestReport, TestScript, ValueSet, VerificationResult, VisionPrescription, Subscription, PractitionerDetails, LocationHierarchy]</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E    },
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E    "issue": [ {
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E      "severity": "error",
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E      "code": "processing",
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E      "diagnostics": "HAPI-0302: Unknown resource type 'practitioner-details' - Server knows how to handle: [Account, ActivityDefinition, AdverseEvent, AllergyIntolerance, Appointment, AppointmentResponse, AuditEvent, Basic, Binary, BiologicallyDerivedProduct, BodyStructure, Bundle, CapabilityStatement, CarePlan, CareTeam, CatalogEntry, ChargeItem, ChargeItemDefinition, Claim, ClaimResponse, ClinicalImpression, CodeSystem, Communication, CommunicationRequest, CompartmentDefinition, Composition, ConceptMap, Condition, Consent, Contract, Coverage, CoverageEligibilityRequest, CoverageEligibilityResponse, DetectedIssue, Device, DeviceDefinition, DeviceMetric, DeviceRequest, DeviceUseStatement, DiagnosticReport, DocumentManifest, DocumentReference, EffectEvidenceSynthesis, Encounter, Endpoint, EnrollmentRequest, EnrollmentResponse, EpisodeOfCare, EventDefinition, Evidence, EvidenceVariable, ExampleScenario, ExplanationOfBenefit, FamilyMemberHistory, Flag, Goal, GraphDefinition, Group, GuidanceResponse, HealthcareService, ImagingStudy, Immunization, ImmunizationEvaluation, ImmunizationRecommendation, ImplementationGuide, InsurancePlan, Invoice, Library, Linkage, ListResource, Location, Measure, MeasureReport, Media, Medication, MedicationAdministration, MedicationDispense, MedicationKnowledge, MedicationRequest, MedicationStatement, MedicinalProduct, MedicinalProductAuthorization, MedicinalProductContraindication, MedicinalProductIndication, MedicinalProductIngredient, MedicinalProductInteraction, MedicinalProductManufactured, MedicinalProductPackaged, MedicinalProductPharmaceutical, MedicinalProductUndesirableEffect, MessageDefinition, MessageHeader, MolecularSequence, NamingSystem, NutritionOrder, Observation, ObservationDefinition, OperationDefinition, OperationOutcome, Organization, OrganizationAffiliation, Parameters, Patient, PaymentNotice, PaymentReconciliation, Person, PlanDefinition, Practitioner, PractitionerRole, Procedure, Provenance, Questionnaire, QuestionnaireResponse, RelatedPerson, RequestGroup, ResearchDefinition, ResearchElementDefinition, ResearchStudy, ResearchSubject, RiskAssessment, RiskEvidenceSynthesis, Schedule, SearchParameter, ServiceRequest, Slot, Specimen, SpecimenDefinition, StructureDefinition, StructureMap, Subscription, Substance, SubstanceNucleicAcid, SubstancePolymer, SubstanceProtein, SubstanceReferenceInformation, SubstanceSourceMaterial, SubstanceSpecification, SupplyDelivery, SupplyRequest, Task, TerminologyCapabilities, TestReport, TestScript, ValueSet, VerificationResult, VisionPrescription, Subscription, PractitionerDetails, LocationHierarchy]"
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E    } ]
2024-01-04 10:15:17.521  9290-9332  LoginViewModel          org.smartregister.opensrp.wdf        E  }
```

**To Reproduce**

**Expected behavior**
User should be able to log into the app.

**Screenshots**
On `opensrp-0.2.5` branch, the following is displayed.
![Screenshot from 2024-01-04 10-10-47](https://github.com/opensrp/fhircore/assets/47570855/1fe968cc-3e84-4151-a42e-f045b4e76fe1)
ch

On `data-migration-prod-apps` branch, the following is displayed.
![Screenshot from 2024-01-04 10-15-32](https://github.com/opensrp/fhircore/assets/47570855/70b675b8-68ec-4a01-a528-d982132e28ec)

**Comment by Rkareko** [comment]
@f-odhiambo @ageryck Log in works for apps pointing to eCBIS preview.

**Comment by ageryck** [comment]
App equally logs in okay in eCHIS Preview as tested by @AbdulWahabMemon

**Comment by Rkareko** [comment]
Closing this since log in works on both eCBIS and eCHIS
