### ISSUE TITLE
 Sync up of resources in bulk not going through 

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#3022]
**Describe the bug**
Issue reported on WDF app on [Sync up of resources in bulk not going through](https://github.com/ona-health/hisp-wdf-fhir-resources/issues/194) ticket.

Executing a  workflow that creates a CarePlan and then updates it within a short time results in sync failure. Both the act of creating and updating the CarePlan result in the creation of  `LocalChangeEntity` entries for the same resource that have the same change log type i.e `INSERT`.
The SDK has a check that prevents the merging of `LocalChangeEntity` records for the same resource that have more than one record of type `INSERT`

The reason that this is not a common bug could be that, in most use-cases, the time between creating and updating  a CarePlan is long enough leading to  the `LocalChangeEntity` records for the 2 processes being processed in different batches. 

**Expected behavior**
Multiple resources registered on the app should sync up successfully.

**Comment by Rkareko** [comment]
The following error is logged when manual sync is initiated 
```
Work [ id=06b80031-ae53-4027-b1e7-460b21c86453, tags={ org.smartregister.fhircore.engine.sync.AppSyncWorker } ] failed because it threw an exception/error
                                                                                                    java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Changes before creation of resource are not permitted
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                                                                                    	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
                                                                                                    	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Changes before creation of resource are not permitted
                                                                                                    	at com.google.android.fhir.sync.upload.patch.PerResourcePatchGenerator.mergeLocalChangesForSingleResource(PerResourcePatchGenerator.kt:50)
                                                                                                    	at com.google.android.fhir.sync.upload.patch.PerResourcePatchGenerator.generate(PerResourcePatchGenerator.kt:39)
                                                                                                    	at com.google.android.fhir.sync.upload.Uploader$upload$2.invokeSuspend(Uploader.kt:49)
                                                                                                    	at com.google.android.fhir.sync.upload.Uploader$upload$2.invoke(Unknown Source:8)
                                                                                                    	at com.google.android.fhir.sync.upload.Uploader$upload$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
                                                                                                    	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
                                                                                                    	at com.google.android.fhir.sync.FhirSynchronizer$upload$2$1.invokeSuspend(FhirSynchronizer.kt:136)
                                                                                                    	at com.google.android.fhir.sync.FhirSynchronizer$upload$2$1.invoke(Unknown Source:8)
                                                                                                    	at com.google.android.fhir.sync.FhirSynchronizer$upload$2$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
                                                                                                    	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
                                                                                                    	at com.google.android.fhir.impl.FhirEngineImpl.syncUpload(FhirEngineImpl.kt:144)
                                                                                                    	at com.google.android.fhir.impl.FhirEngineImpl$syncUpload$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Rkareko** [comment]
This is issue is caused by having 2 entries in the `LocalChangeEntity` table of type `INSERT` for a resource with the same id

sample entries

```
LocalChange(resourceType=CarePlan, resourceId=c1f58fac-7928-489b-b038-d2e4e07fa369, versionId=null, timestamp=2024-01-29T14:31:58.554Z, type=INSERT, payload={"resourceType":"CarePlan","id":"c1f58fac-7928-489b-b038-d2e4e07fa369","meta":{"lastUpdated":"2024-01-29T17:31:58.553+03:00","tag":[{"system":"https://smartregister.org/care-team-tag-id","code":"3e005baf-854b-40a7-bdd5-9b73f63aa9a3","display":"Practitioner CareTeam"},{"system":"https://smartregister.org/location-tag-id","code":"103967","display":"Practitioner Location"},{"system":"https://smartregister.org/organisation-tag-id","code":"41eae946-bdc4-4179-b404-6503ff12f59c","display":"Practitioner Organization"},{"system":"https://smartregister.org/practitioner-tag-id","code":"49b72a3d-44cd-4a74-9459-4dc9f6b543fa","display":"Practitioner"},{"system":"https://smartregister.org/app-version","code":"Not defined","display":"Application Version"}]},"instantiatesCanonical":["PlanDefinition/dc-diabetes-screening-intervention"],"status":"active","intent":"plan","title":"Schedule of screening & follow-ups for registered patients","description":"Schedule of screening & follow-ups for registered patients","subject":{"reference":"Patient/e941c05a-0752-4563-919c-45f46815384a"},"period":{"start":"2024-01-29T17:31:58+03:00"},"created":"2024-01-29T17:31:58+03:00","author":{"reference":"Practitioner/49b72a3d-44cd-4a74-9459-4dc9f6b543fa"},"activity":[{"outcomeReference":[{"reference":"Task/8b57ff8c-ed6b-4fab-a13d-cd488ebef10e"}],"detail":{"kind":"Task","status":"in-progress","performer":[{"reference":"Practitioner/49b72a3d-44cd-4a74-9459-4dc9f6b543fa"}],"description":"This will initialize Diabetes Screening CarePlan"}}]}, token=LocalChangeToken(ids=[8]))
```
and 

```
LocalChange(resourceType=CarePlan, resourceId=c1f58fac-7928-489b-b038-d2e4e07fa369, versionId=null, timestamp=2024-01-29T14:32:32.879Z, type=INSERT, payload={"resourceType":"CarePlan","id":"c1f58fac-7928-489b-b038-d2e4e07fa369","meta":{"lastUpdated":"2024-01-29T17:32:32.878+03:00","tag":[{"system":"https://smartregister.org/care-team-tag-id","code":"3e005baf-854b-40a7-bdd5-9b73f63aa9a3","display":"Practitioner CareTeam"},{"system":"https://smartregister.org/location-tag-id","code":"103967","display":"Practitioner Location"},{"system":"https://smartregister.org/organisation-tag-id","code":"41eae946-bdc4-4179-b404-6503ff12f59c","display":"Practitioner Organization"},{"system":"https://smartregister.org/practitioner-tag-id","code":"49b72a3d-44cd-4a74-9459-4dc9f6b543fa","display":"Practitioner"},{"system":"https://smartregister.org/app-version","code":"Not defined","display":"Application Version"}]},"instantiatesCanonical":["PlanDefinition/dc-diabetes-screening-intervention"],"status":"active","intent":"plan","title":"Schedule of screening & follow-ups for registered patients","description":"Schedule of screening & follow-ups for registered patients","subject":{"reference":"Patient/e941c05a-0752-4563-919c-45f46815384a"},"period":{"start":"2024-01-29T17:31:58+03:00"},"created":"2024-01-29T17:31:58+03:00","author":{"reference":"Practitioner/49b72a3d-44cd-4a74-9459-4dc9f6b543fa"},"activity":[{"outcomeReference":[{"reference":"Task/8b57ff8c-ed6b-4fab-a13d-cd488ebef10e"},{"reference":"Task/042b542d-018f-46a7-9768-31c0a844d36e"}],"detail":{"kind":"Task","status":"in-progress","performer":[{"reference":"Practitioner/49b72a3d-44cd-4a74-9459-4dc9f6b543fa"}],"description":"This will initialize Diabetes Screening CarePlan"}}]}, token=LocalChangeToken(ids=[27]))
```
