### ISSUE TITLE
Test coverage for the Quest module not generated correctly.

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#3055]
**Describe the Issue**
The command used on [main branch](https://github.com/opensrp/fhircore/blob/main/.github/workflows/ci.yml#L224) fails on this branch with the following error

**Command:**
```shell
./gradlew -PlocalPropertiesFile=local.properties :quest:clean && ./gradlew -PlocalPropertiesFile=local.properties :quest:assembleOpensrpDebugAndroidTest --stacktrace && /Users/runner/Library/Android/sdk/platform-tools/adb install quest/build/outputs/apk/androidTest/opensrp/debug/quest-opensrp-debug-androidTest.apk && ./gradlew -PlocalPropertiesFile=local.properties :quest:assembleOpensrpDebug --stacktrace && /Users/runner/Library/Android/sdk/platform-tools/adb install quest/build/outputs/apk/opensrp/debug/quest-opensrp-debug.apk && /Users/runner/Library/Android/sdk/platform-tools/adb shell am instrument -w -e package org.smartregister.fhircore.quest.ui.profile -e coverage "true" org.smartregister.opensrp.test/org.smartregister.fhircore.quest.QuestTestRunner && /Users/runner/Library/Android/sdk/platform-tools/adb shell run-as org.smartregister.opensrp cat "/data/user/0/org.smartregister.opensrp/files/coverage.ec" > quest/coverage.ec && ./gradlew -PlocalPropertiesFile=local.properties :quest:fhircoreJacocoReport --stacktrace
```

**Error** 
```
Error: Failed to generate Emma/JaCoCo coverage. Is Emma/JaCoCo jar on classpath?
Generated code coverage data to /data/user/0/org.smartregister.opensrp/files/coverage.ec
cat: /data/user/0/org.smartregister.opensrp/files/coverage.ec: No such file or directory
Error: The process '/bin/sh' failed with exit code 1
```

Enabling test coverage in the build file using the following debug configs results in the error logged  [here ](https://github.com/opensrp/fhircore/actions/runs/6862154977/job/18659297852?pr=2825)
```
android {
    ...
    buildTypes {
      debug {
		  enableAndroidTestCoverage = true
		  enableUnitTestCoverage = true
     }
        ...
    }
}
```

The specific error that emerged after this upgrade is 
```
Caused by: java.io.IOException: Error while instrumenting org/hl7/fhir/r5/formats/JsonParser.class with JaCoCo 0.8.11.202310140853/f33756c.
	at org.jacoco.core.instr.Instrumenter.instrumentError(Instrumenter.java:161)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:111)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:136)
	... 123 more
Caused by: org.objectweb.asm.ClassTooLargeException: Class too large: org/hl7/fhir/r5/formats/JsonParser
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:622)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:92)
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:109)
```

**Comment by ndegwamartin** [comment]
The related PR that introduced the issue is [Upgrade sdk libraries to latest versions #2825](https://github.com/opensrp/fhircore/pull/2825)

**Comment by ndegwamartin** [comment]
This issue is reported on HAPI FHIR repo as well : https://github.com/hapifhir/hapi-fhir/issues/5210

**Comment by ndegwamartin** [comment]
Attaching the full stacktrace - [jacoco_full_stacktrace.txt](https://github.com/user-attachments/files/16314822/jacoco_full_stacktrace.txt)
