### ISSUE TITLE
Saving a questionnaire with nested repeatedGroup items fails with crash

### ISSUE THREAD

**Issue by LZRS** [opensrp/fhircore#3245]
**To Reproduce**
1. Open a questionnaire with a repeated group item
2. Repeatedly fill the group to at least 3 or more times
3. Submit the questionnaire and it crashes

**Additional context**
```
java.lang.IllegalArgumentException: Missing questionnaire item for questionnaire response item blood-pressure-repeating-group
                                                                                                    	at com.google.android.fhir.datacapture.validation.QuestionnaireResponseValidator.validateQuestionnaireResponseItems(QuestionnaireResponseValidator.kt:120)
                                                                                                    	at com.google.android.fhir.datacapture.validation.QuestionnaireResponseValidator.validateQuestionnaireResponseItem(QuestionnaireResponseValidator.kt:160)
                                                                                                    	at com.google.android.fhir.datacapture.validation.QuestionnaireResponseValidator.validateQuestionnaireResponseItems(QuestionnaireResponseValidator.kt:133)
                                                                                                    	at com.google.android.fhir.datacapture.validation.QuestionnaireResponseValidator.validateQuestionnaireResponse(QuestionnaireResponseValidator.kt:93)
                                                                                                    	at com.google.android.fhir.datacapture.validation.QuestionnaireResponseValidator.validateQuestionnaireResponse$default(QuestionnaireResponseValidator.kt:57)
                                                                                                    	at org.smartregister.fhircore.quest.ui.questionnaire.QuestionnaireViewModel.validateQuestionnaireResponse(QuestionnaireViewModel.kt:731)
                                                                                                    	at org.smartregister.fhircore.quest.ui.questionnaire.QuestionnaireViewModel$handleQuestionnaireSubmission$1.invokeSuspend(QuestionnaireViewModel.kt:242)
```

__experienced in WDF__

**Comment by pld** [comment]
is this an Android FHIR SDK error?
