### ISSUE TITLE
Investigate P2P sync failure on some devices

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#3442]
**Describe the issue to be investigated**
When sending data via p2p, on some devices, especially if the devices are not of the same model, they are failing to pair.
As described on [[Prod apk] P2P failing to pair on some devices](https://github.com/onaio/fhir-resources/issues/2677) ticket the following issues were observed :- 

- The devices were not pairing, note that, they were from different models, and it seems the challenge was not primarily on just Samsung - The other issue probably reported in a different ticket was even after pairing for the p2p sync % was not progressing between samsung and G60.

**Comment by Rkareko** [comment]
Research has shown that a probable cause for some devices failing to pair is a requirement that apps which target Android 13 (API level 33) and manage Wi-Fi connections should request the [ NEARBY_WIFI_DEVICES](https://developer.android.com/reference/android/Manifest.permission#NEARBY_WIFI_DEVICES) runtime permission according to [these docs](https://developer.android.com/develop/connectivity/wifi/wifi-permissions) This permission is required for peer discovery and requesting peers, requesting devices info among other functionality that is used in P2P sync

[Request for NEARBY_WIFI_DEVICES permission for Android 13 and higher](https://github.com/onaio/android-p2p/issues/76) github ticket will track the implementation for requesting this permission on the p2p-lib.

**Comment by ageryck** [comment]
There's a need for QA P2P feature on Samsung devices with Android versions lower than 13 (preferably 11 & 12), the test should cover the following;
- [ ] ability to pair and sync data via P2P
- [ ] ability to load in-app reports correctly

**Comment by madrinekariuki** [comment]
QA done using `Nokia G22 android 13` on OpenSRP 0.2.5 branch on eCBIS.
See below findings:
- Initial P2P Fails on the sender device and an `search failed error `is returned. 
  to be able to proceed (being able to search for  a device to pair with and pair), one has to exit the transfer module on both devices and open it again. 
- after successfully pairing the device, as the devices are preparing to send data, this   fails .

Error Logs:
```
2024-08-28 12:04:22.348 21267-22434 WifiDirect...rverSocket org.smartregister.opensrp.ecbis      E  java.net.SocketTimeoutException: Poll timed out
                                                                                                    	at libcore.io.IoBridge.poll(IoBridge.java:866)
                                                                                                    	at java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:196)
                                                                                                    	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:451)
                                                                                                    	at java.net.ServerSocket.implAccept(ServerSocket.java:569)
                                                                                                    	at java.net.ServerSocket.accept(ServerSocket.java:537)
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$acceptConnectionsToServerSocket$2.invokeSuspend(WifiDirectDataSharingStrategy.kt:619)
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$acceptConnectionsToServerSocket$2.invoke(Unknown Source:8)
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$acceptConnectionsToServerSocket$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy.acceptConnectionsToServerSocket(WifiDirectDataSharingStrategy.kt:611)
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy.makeSocketConnections(WifiDirectDataSharingStrategy.kt:598)
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$send$1.invokeSuspend(WifiDirectDataSharingStrategy.kt:493)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-08-28 12:04:22.350 21267-22434 P2PSenderV...iceDetails org.smartregister.opensrp.ecbis      E  An error occurred trying to setup the socket
                                                                                                    java.lang.Exception: An exception occurred and the socket is null
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$send$1$1.invoke(WifiDirectDataSharingStrategy.kt:512)
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$send$1$1.invoke(WifiDirectDataSharingStrategy.kt:493)
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy.makeSocketConnections(WifiDirectDataSharingStrategy.kt:607)
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$send$1.invokeSuspend(WifiDirectDataSharingStrategy.kt:493)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-08-28 12:04:22.400 21267-21267 WifiDirect...ngStrategy org.smartregister.opensrp.ecbis      D  disconnect successfull
2024-08-28 12:04:22.402 21267-21267 BaseViewMo...disconnect org.smartregister.opensrp.ecbis      I  Disconnection successful
2024-08-28 12:04:22.402 21267-21267 P2PViewModel            org.smartregister.opensrp.ecbis      I  P2P state updated to DEVICE_DISCONNECTED
2024-08-28 12:04:22.446 21267-21267 BottomShee...ottomSheet org.smartregister.opensrp.ecbis      D  BottomSheetScreen: Device Role: SENDER
2024-08-28 12:04:22.447 21267-21267 BottomShee...ottomSheet org.smartregister.opensrp.ecbis      D  BottomSheetScreen: P2P State: DEVICE_DISCONNECTED
2024-08-28 12:04:22.447 21267-21267 BottomShee...ottomSheet org.smartregister.opensrp.ecbis      D  BottomSheetScreen: Devices list 1
2024-08-28 12:04:22.447 21267-21267 BottomShee...ottomSheet org.smartregister.opensrp.ecbis      D  Device list Else p2p state. State is DEVICE_DISCONNECTED
2024-08-28 12:04:23.015 21267-21267 WifiP2pBro...stReceiver org.smartregister.opensrp.ecbis      E  Wifi p2p Connection changed action
2024-08-28 12:04:23.016 21267-21267 WifiDirect...nitChannel org.smartregister.opensrp.ecbis      E  onConnectionInfoAvailable() WIFIp2p Group is null
2024-08-28 12:04:23.016 21267-21267 WifiDirect...nitChannel org.smartregister.opensrp.ecbis      E  onConnectionInfoAvailable() Paired: false
2024-08-28 12:04:23.017 21267-21267 WifiDirect...nitChannel org.smartregister.opensrp.ecbis      E  onConnectionInfoAvailable() Requested disconnection: true
2024-08-28 12:04:23.017 21267-21267 WifiDirect...ngStrategy org.smartregister.opensrp.ecbis      D  Connection info available: groupFormed = false, isGroupOwner = false
2024-08-28 12:04:23.018 21267-22434 WifiDirect...ategy$send org.smartregister.opensrp.ecbis      E  groupOwnerAddress is null
2024-08-28 12:04:23.019 21267-22434 P2PSenderV...iceDetails org.smartregister.opensrp.ecbis      E  An error occurred trying to setup the socket
                                                                                                    java.lang.Exception: An exception occurred and the groupOwnerAddress is null
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$send$1.invokeSuspend(WifiDirectDataSharingStrategy.kt:486)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-08-28 12:04:23.026 21267-21267 WifiDirect...ngStrategy org.smartregister.opensrp.ecbis      D  Successfully stopped peer discovery
2024-08-28 12:04:23.030 21267-21267 P2PViewMod...eviceFound org.smartregister.opensrp.ecbis      I  onDeviceFound: State is DEVICE_DISCONNECTED
2024-08-28 12:04:23.030 21267-21267 P2PViewMod...eviceFound org.smartregister.opensrp.ecbis      I  Devices searching succeeded. Found 0 devices
2024-08-28 12:04:23.031 21267-21267 WifiDirect...ngStrategy org.smartregister.opensrp.ecbis      D  disconnect failed
2024-08-28 12:04:23.032 21267-21267 BaseViewMo...disconnect org.smartregister.opensrp.ecbis      E  P2P diconnection failed
                                                                                                    java.lang.Exception: Error #2: Busy
                                                                                                    	at org.smartregister.p2p.data_sharing.WifiDirectDataSharingStrategy$disconnect$1.onFailure(WifiDirectDataSharingStrategy.kt:454)
                                                                                                    	at android.net.wifi.p2p.WifiP2pManager$Channel$P2pHandler.handleMessage(WifiP2pManager.java:1292)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8057)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
2024-08-28 12:04:23.034 21267-21267 P2PViewModel            org.smartregister.opensrp.ecbis      I  P2P state updated to DEVICE_DISCONNECTED

```

**Comment by madrinekariuki** [comment]
@Rkareko [This](https://github.com/opensrp/fhircore/issues/3442#issuecomment-2314856204) passes QA , on the error on the initial pairing request.
tested this on  below devices:

- nokia to nokia
- samsung to nokia
- nokia  to samsung
- g60 to g60
- g60 to samsung
- samsung to g60
- g60 to nokia
- nokia t0 g60

**Comment by Mstjamush** [comment]
@Rkareko 
I've tested on these devices too and working as expected

- Techno spark 20c to Samsung A25
- Techno Spark 7 to Samsung A12

**Comment by madrinekariuki** [comment]
@Rkareko  
apk: https://onaio.slack.com/archives/C0E2558SH/p1725527632562549

`samsung A15 Android 14`
`Redmi A3x 4 GB RAM android 14`
`Nokia G22 android 13`

This is failing on android 14  devices see details below:
-  for below pair requests the observations are similar:
`samsung A15 to Redmi A3x`
`samsung A15 to nokia `
 `nokia to RedMi`
   - Fails to pair on the sender device on initial pair request.
   - pairs after exiting the module and reopening it.
   - after pairing is successful, the data is transferred successful and the data is correct
   screenshot
   
![Screenshot 2024-09-06 at 14 44 20](https://github.com/user-attachments/assets/1e2a3e58-a13f-4908-a70d-1dc9bf4838c3)

**Comment by Rkareko** [comment]
> RedMi to samsung A15:
pairs well but fails on sending data sender gets stuck at 2% and receiver gets stuck at 0% and then P2P fails with the error below:

@madrinekariuki could you test whether the error noted above happens when transferring data from the `RedMi` to other devices in addition to the Samsung device?

**Comment by madrinekariuki** [comment]
> > RedMi to samsung A15:
> > pairs well but fails on sending data sender gets stuck at 2% and receiver gets stuck at 0% and then P2P fails with the error below:
> 
> @madrinekariuki could you test whether the error noted above happens when transferring data from the `RedMi` to other devices in addition to the Samsung device?

@Rkareko I am able to successfully transfer data in other devices from the` Redmi A3x 4 GB RAM android 14`
I have used:

`Redmi to Blu G60 android 9`
`Redmi to Samsung A12 android 11`

**Comment by Rkareko** [comment]
> nb// below issue is not happening all the times but reporting it as it has been observed a couple of times on samsung A15 to nokia G22 and nokia G22 to samsung A15.
the observations are:

    Fails to pair on the sender device on initial pair request.
    pairs after exiting the module and reopening it.
    after pairing is successful, the data is transferred successful and the data is correct
    screenshot on the error

@madrinekariuki couple of questions
1. Does this happen to devices of the same brand e.g samsung A15 (android 14) and Samsung A25(Android 14) 
2. Has this been observed on other combinations of devices apart from the samsung A15 (android 14) and the Nokia G22 (Android 13)
3. What happens when trying to pair the devices after the initial pairing failure without exiting the module?

**Comment by madrinekariuki** [comment]
@Rkareko find my responses in Italics below:
1. Does this happen to devices of the same brand e.g samsung A15 (android 14) and Samsung A25(Android 14)
   _no, transfer starts and works well. e.g tested this on, samsung A15(android 14) to samsung A12 (android 11) , I do not have android 14 devices of the same brand_
2. Has this been observed on other combinations of devices apart from the samsung A15 (android 14) and the Nokia G22 (Android 13)
  _no, other combinations of the devices that i have are working well. tested on Redmi  (android 14) to Samsung A12 ( android 11)_

3. What happens when trying to pair the devices after the initial pairing failure without exiting the module?

**Comment by madrinekariuki** [comment]
> @Rkareko find my responses in Italics below:
> 
> 1. Does this happen to devices of the same brand e.g samsung A15 (android 14) and Samsung A25(Android 14)
>    _no, transfer starts and works well. e.g tested this on, samsung A15(android 14) to samsung A12 (android 11) , I do not have android 14 devices of the same brand_
> 2. Has this been observed on other combinations of devices apart from the samsung A15 (android 14) and the Nokia G22 (Android 13)
>    _no, other combinations of the devices that i have are working well. tested on Redmi  (android 14) to Samsung A12 ( android 11)_
> 3. What happens when trying to pair the devices after the initial pairing failure without exiting the module?
>    _I have not managed to replicate this issue today, will update this when i experience this error again._

@Rkareko 
On further testing, I have not been able to replicate this issue again between the Samsung A15 android 14 and Nokia G22 android 13. I will be on the look out incase it happens.

Also to note that there is a work around on this incase it happens again. (i.e exiting the transfer module and re-opening it) and one can progress with the P2P transfer successfully.

cc @Gental-Giant @ageryck @Mstjamush

**Comment by madrinekariuki** [comment]
@Rkareko cc @Gental-Giant @Mstjamush 

retests were conducted using this shared release apk using the following devices
`Redmi  android 14`
`Samsung A15 android 14`
`Samsung A25 android 14`
`Nokia G22 android 13`

the regression tests were mainly to retest the 2 items and the entire  p2p functionality. Find the test findings in italics and the issues 
the issues were:
1. **pairs well but fails on sending data sender gets stuck at  a certain % and receiver gets stuck at a certain % and then P2P fails with an error. (this was mostly being observed on android 14 devices especially Redmi to Samsung).**
 _The issue does not happen all the time and it seems to only happen on Redmi to Samsung A15 and Samsung 15 to redmi._ 
2. **the intermitent error on initial pairing, where we get an error 'device disconnected'.**
  This is still an issue that does not happen all the time , but when it happens and you retry the data transfer, it is successful . 
  
new issue:
3. on auto-rotate mode i.e when you tilt your device during transfer, P2P stops.
