### ISSUE TITLE
Transaction Too Large Error when saving a photo taken on a form

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3578]
**Describe the feature request.**
- App force closes when saving a form with a photo attached.
- The form QR is extracted correctly.   

**Additional context**
```cli
Second failure launching org.smartregister.opensrp.eusmMg/org.smartregister.fhircore.quest.ui.main.AppMainActivity, giving up (Ask Gemini)
                                                                                                    android.os.TransactionTooLargeException: data parcel size 568752 bytes
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:624)
                                                                                                    	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2750)
                                                                                                    	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
                                                                                                    	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
                                                                                                    	at com.android.server.wm.ActivityTaskSupervisor.realStartActivityLocked(ActivityTaskSupervisor.java:935)
                                                                                                    	at com.android.server.wm.ActivityTaskSupervisor.startSpecificActivity(ActivityTaskSupervisor.java:1069)
                                                                                                    	at com.android.server.wm.Task.resumeTopActivityInnerLocked(Task.java:7597)
                                                                                                    	at com.android.server.wm.Task.resumeTopActivityUncheckedLocked(Task.java:7074)
                                                                                                    	at com.android.server.wm.Task.resumeTopActivityUncheckedLocked(Task.java:7128)
                                                                                                    	at com.android.server.wm.ActivityRecord.makeActiveIfNeeded(ActivityRecord.java:5946)
                                                                                                    	at com.android.server.wm.EnsureActivitiesVisibleHelper.setActivityVisibilityState(EnsureActivitiesVisibleHelper.java:199)
                                                                                                    	at com.android.server.wm.EnsureActivitiesVisibleHelper.lambda$process$0$EnsureActivitiesVisibleHelper(EnsureActivitiesVisibleHelper.java:108)
                                                                                                    	at com.android.server.wm.EnsureActivitiesVisibleHelper$$ExternalSyntheticLambda0.accept(Unknown Source:8)
                                                                                                    	at com.android.server.wm.ActivityRecord.forAllActivities(ActivityRecord.java:4576)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1511)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1505)
                                                                                                    	at com.android.server.wm.EnsureActivitiesVisibleHelper.process(EnsureActivitiesVisibleHelper.java:107)
                                                                                                    	at com.android.server.wm.Task.lambda$ensureActivitiesVisible$23(Task.java:6947)
                                                                                                    	at com.android.server.wm.Task$$ExternalSyntheticLambda26.accept(Unknown Source:10)
                                                                                                    	at com.android.server.wm.Task.forAllLeafTasks(Task.java:4564)
                                                                                                    	at com.android.server.wm.Task.ensureActivitiesVisible(Task.java:6947)
                                                                                                    	at com.android.server.wm.DisplayContent.lambda$ensureActivitiesVisible$44(DisplayContent.java:6111)
                                                                                                    	at com.android.server.wm.DisplayContent$$ExternalSyntheticLambda18.accept(Unknown Source:10)
                                                                                                    	at com.android.server.wm.Task.forAllRootTasks(Task.java:4576)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1824)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1824)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1824)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1824)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1824)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1824)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1817)
                                                                                                    	at com.android.server.wm.DisplayContent.ensureActivitiesVisible(DisplayContent.java:6110)
                                                                                                    	at com.android.server.wm.RootWindowContainer.ensureActivitiesVisible(RootWindowContainer.java:2062)
                                                                                                    	at com.android.server.wm.RootWindowContainer.ensureActivitiesVisible(RootWindowContainer.java:2043)
                                                                                                    	at com.android.server.wm.Task.completePauseLocked(Task.java:6879)
                                                                                                    	at com.android.server.wm.ActivityRecord.activityPaused(ActivityRecord.java:6174)
                                                                                                    	at com.android.server.wm.ActivityClientController.activityPaused(ActivityClientController.java:180)
                                                                                                    	at android.app.IActivityClientController$Stub.onTransact(IActivityClientController.java:540)
                                                                                                    	at com.android.server.wm.ActivityClientController.onTransact(ActivityClientController.java:117)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1187)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1146)
```

**Acceptance criteria**
- [ ] Forms with photos should be saved and extracted correctly.  
- [ ] The app should not force close

**Area path**
A list of ordered steps in the app on the usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the EUSM app
2. Open a service point profile
3. Click on one of the product checks and make sure you take a photo of the product
4. Save the form

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _checklist_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by dubdabasoduba** [comment]
@ellykits @ndegwamartin I am going to close this since it hasn't been replicated
