### ISSUE TITLE
Fix OutOfMemoryException

### ISSUE THREAD

**Issue by owais-vd** [opensrp/fhircore#583]
**Describe the Issue**

We are having **OutOfMemoryException** on two test files in this PR #541 that need to be investigated.

- [x] [StructureMapTestUtilities](https://github.com/opensrp/fhircore/blob/issue-536/android/eir/src/test/java/org/smartregister/fhircore/engine/StructureMapTestUtilities.kt)
- [x] [DateTimeExtensionTest](https://github.com/opensrp/fhircore/blob/main/android/engine/src/test/java/org/smartregister/fhircore/engine/util/extension/DateTimeExtensionTest.kt)

**Comment by f-odhiambo** [comment]
This is happening randomly and needs to be further investigated. Adding blocked label for now

**Comment by pld** [comment]
Do we know the code merge after which this started happening? Could this be related to the CQL library? We know that requires a large amount of memory

**Comment by syedowaisali90** [comment]
might be, the first time in this PR https://github.com/opensrp/fhircore/pull/523 some tests had been disabled. cc: @ellykits @ndegwamartin

**Comment by maimoonak** [comment]
```

 02:07:52.681 31793-31793/? W/adbd: timeout expired while flushing socket, closing
02:07:52.759 3616-3616/? E/crash_dump64: unknown process state: t
02:07:52.829 3865-3865/? E/audit: type=1400 audit(1635887272.825:21126): avc:  denied  { dac_override } for  pid=3620 comm="crash_dump64" capability=1  scontext=u:r:crash_dump:s0 tcontext=u:r:crash_dump:s0 tclass=capability permissive=0 SEPF_SM-A307FN_10_0027 audit_filtered
02:07:52.830 3865-3865/? E/audit: type=1327 audit(1635887272.825:21126): 
02:07:52.851 3621-3621/? E/DEBUG: failed to open directory /proc/3880/fd: Permission denied
02:07:52.852 3621-3621/? W/crash_dump64: failed to attach to thread 3461, already traced by 0 ()
02:07:52.855 3621-3621/? W/crash_dump64: failed to ptrace interrupt thread 3465: No such process
02:07:52.856 3621-3621/? A/crash_dump64: crash_dump.cpp:535] failed to attach to thread 3880, already traced by 0 ()
02:07:52.858 4026-4026/? W//system/bin/tombstoned: crash socket received short read of length 0 (expected 12)
    
    --------- beginning of crash
02:07:52.859 3880-3880/? A/libc: crash_dump helper failed to exec
02:07:52.909 3624-3624/? E/crash_dump32: unknown process state: t
02:07:52.934 3881-3881/? A/libc: failed to wait for crash_dump helper: No child processes
02:07:54.719 4378-4422/? E/Watchdog: !@Sync 11406 [02:07:54.718] FD count : 585, wdog_way : softdog
02:07:58.094 4378-4589/? E/ActivityManager: ANR in fhircore.quest (fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity)
    PID: 431
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 7.  Wait queue head age: 99110.0ms.)
    Parent: fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity
    Load: 21.03 / 21.33 / 20.78
    CPU usage from 0ms to 7706ms later (02:07:50.296 to 02:07:58.002):
      149% 431/fhircore.quest: 133% user + 15% kernel / faults: 23751 minor
      33% 3923/surfaceflinger: 18% user + 14% kernel / faults: 394 minor
      25% 4378/system_server: 12% user + 13% kernel / faults: 5007 minor 64 major
      14% 3894/android.hardware.graphics.composer@2.1-service: 4.2% user + 10% kernel / faults: 464 minor
      7.2% 2049/decon0: 0% user + 7.2% kernel
      1.2% 3990/media.codec: 0.8% user + 0.3% kernel / faults: 9125 minor
      6.6% 6372/com.google.android.googlequicksearchbox:interactor: 5.7% user + 0.9% kernel / faults: 617 minor 2 major
      4.7% 3885/android.hardware.audio@2.0-service: 2.9% user + 1.8% kernel
      3.9% 6688/com.sec.android.app.shealth:remote: 2.5% user + 1.4% kernel / faults: 402 minor
      3.7% 3898/android.hardware.sensors@1.0-service: 1.4% user + 2.3% kernel
      0.6% 4007/media.swcodec: 0.2% user + 0.3% kernel / faults: 5437 minor
      0.5% 3978/media.extractor: 0.1% user + 0.3% kernel / faults: 3574 minor
      2.4% 3450/kworker/u17:2: 0% user + 2.4% kernel
      2.3% 3604/kworker/3:1: 0% user + 2.3% kernel
      2.3% 3920/audioserver: 1.5% user + 0.7% kernel / faults: 137 minor
      2.1% 31793/adbd: 0.7% user + 1.4% kernel / faults: 247 minor
      1.6% 29712/kworker/u17:1: 0% user + 1.6% kernel
      1.5% 30426/kworker/u16:1: 0% user + 1.5% kernel
      1.4% 7/rcu_preempt: 0% user + 1.4% kernel
      1.1% 3665/logd: 0.3% user + 0.7% kernel / faults: 7 minor
      1% 883/cfinteractive: 0% user + 1% kernel
      1% 3241/kworker/0:0: 0% user + 1% kernel / faults: 16 minor
      0.9% 2894/ueventd: 0.7% user + 0.1% kernel / faults: 6 minor
      0.7% 30894/kworker/u16:5: 0% user + 0.7% kernel
      0.6% 4758/com.android.systemui: 0.6% user + 0% kernel / faults: 29 minor
      0% 8/rcu_sched: 0% user + 0% kernel
      0.5% 2047/decon0-vsync: 0% user + 0.5% kernel
      0.5% 4857/com.sec.location.nsflp2: 0.3% user + 0.1% kernel / faults: 71 minor
      0% 31735/kworker/u16:2: 0% user + 0% kernel
      0.3% 1/init: 0.1% user + 0.2% kernel
      0.3% 1805/kworker/3:0: 0% user + 0.3% kernel
      0% 4026/tombstoned: 0% user + 0% kernel
      0.2% 39/migration/5: 0% user + 0.2% kernel
      0% 3880/zygote64: 0% user + 0% kernel / faults: 14 minor
      0% 3881/zygote: 0% user + 0% kernel / faults: 14 minor
      0.2% 5661/com.android.bluetooth: 0% user + 0.2% kernel / faults: 119 minor
      0% 3/ksoftirqd/0: 0% user + 0% kernel
      0.1% 1446/kworker/5:1: 0% user + 0.1% kernel
      0.1% 1790/mmc-cmdqd/0: 0% user + 0.1% kernel
      0.1% 2084/com.facebook.katana: 0% user + 0.1% kernel / faults: 6 minor
      0.1% 3500/kworker/2:0: 0% user + 0.1% kernel
      0.1% 3598/kworker/1:2: 0% user + 0.1% kernel
      0% 3686/vold: 0% user + 0% kernel / faults: 45 minor
      0.1% 3728/jbd2/mmcblk0p32: 0% user + 0.1% kernel
      0% 3826/vendor.samsung.hardware.security.proca@2.0-service: 0% user + 0% kernel / faults: 18 minor
      0% 3963/cameraserver: 0% user + 0% kernel / faults: 69 minor
      0% 3965/drmserver: 0% user + 0% kernel / faults: 19 minor
      0% 3971/diagexe: 0% user + 0% kernel
      0% 3974/installd: 0% user + 0% kernel / faults: 33 minor
      0% 3979/media.metrics: 0% user + 0% kernel / faults: 22 minor
      0% 3980/mediaserver: 0% user + 0% kernel / faults: 27 minor
      0% 3982/remotedisplay: 0% user + 0% kernel / faults: 16 minor
      0.1% 3987/statsd: 0% user + 0.1% kernel / faults: 24 minor
      0% 3988/storaged: 0% user + 0% kernel / faults: 1 minor
      0.1% 3994/argosd: 0% user + 0.1% kernel
      0.1% 6492/com.sec.android.sdhms: 0.1% user + 0% kernel / faults: 40 minor
      0.1% 
02:07:58.096 4378-4589/? W/ActivityManager: anr : fhircore.quest,10566
02:07:58.100 4378-4416/? W/Looper: Slow dispatch took 3386ms android.fg h=android.os.Handler c=com.android.server.Watchdog$HandlerChecker@3781acb m=0
02:07:58.107 4378-4416/? W/Looper: Slow delivery took 445ms android.fg h=com.android.server.usb.UsbDeviceManager$UsbHandlerLegacy c=null m=9
02:07:58.111 3426-3426/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1631 android.content.ContextWrapper.startService:683 com.samsung.android.sm.battery.receiver.BatteryReceiver.c:6 com.samsung.android.sm.battery.receiver.BatteryReceiver.onReceive:16 android.app.ActivityThread.handleReceiver:4116 
02:07:58.150 3426-3702/? W/SmsApplication: Package com.google.android.talk lacks required manifest declarations to be a default sms app:  mPackageName: com.google.android.talk mSmsReceiverClass: com.google.android.apps.hangouts.sms.SmsDeliverReceiver mMmsReceiverClass: com.google.android.apps.hangouts.sms.MmsWapPushDeliverReceiver mRespondViaMessageClass: null mSendToClass: com.google.android.apps.hangouts.phone.BabelHomeActivity mSmsAppChangedClass: null mProviderChangedReceiverClass: null mSimFullReceiverClass: null mUid: 10213
02:07:58.192 3426-3702/? W/AppErrorNotification: Skip. fhircore.questis excluded
02:07:58.201 4378-4417/? E/DecorView: mWindow.mActivityCurrentConfig is null
02:07:58.202 4378-4650/? W/Looper: Drained
02:07:58.202 4378-4416/? W/Looper: Drained
02:07:58.207 4378-4425/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
02:07:58.218 4378-4425/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
02:07:58.302 4378-4417/? E/DecorView: mWindow.mActivityCurrentConfig is null
02:07:58.304 3923-5645/? E/BufferQueueProducer: [Application Not Responding: fhircore.quest#0] disconnect: not connected (req=1)
02:07:58.304 4378-26112/? W/libEGL: EGLNativeWindowType 0x7cb117a290 disconnect failed
02:07:59.893 4378-4417/? E/DecorView: mWindow.mActivityCurrentConfig is null
02:07:59.964 3923-5645/? E/BufferQueueProducer: [Application Not Responding: fhircore.quest#0] disconnect: not connected (req=1)
02:07:59.964 4378-26112/? W/libEGL: EGLNativeWindowType 0x7d129c5990 disconnect failed
02:07:59.977 4378-4417/? E/ViewRootImpl: sendUserActionEvent() mView returned.
02:07:59.977 4378-6532/? E/InputDispatcher: Window handle Window{eab67a0 u0 Application Not Responding: fhircore.quest} has no registered input channel
02:08:08.553 4378-4625/? E/MobileWipsFrameworkService: unbinded can not send 12
02:08:09.909 4378-4625/? E/MobileWipsFrameworkService: unbinded can not send 13
02:08:09.913 30144-30144/? W/[+5]oneconnect[1.7.73.22_01][CORE]: P2pReceiver.handleScanResultsAvailableAction - No Permission
02:08:13.686 431-431/fhircore.quest W/.fhircore.ques: Throwing OutOfMemoryError "Failed to allocate a 294920 byte allocation with 286752 free bytes and 280KB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 6500136 kB)
02:08:13.771 3923-4003/? E/BufferQueueProducer: [StatusBar$_4758#0] disconnect: not connected (req=1)
02:08:13.771 4758-5461/? W/libEGL: EGLNativeWindowType 0x7cbc4ff090 disconnect failed
02:08:13.781 4758-4758/? W/View: requestLayout() improperly called by android.view.SurfaceView{808c956 V.E...... ......I. 0,0-0,0} during layout: running second layout pass
02:08:15.373 3923-5645/? E/BufferQueueProducer: [StatusBar$_4758#0] disconnect: not connected (req=1)
02:08:15.373 4758-5461/? W/libEGL: EGLNativeWindowType 0x7c74872890 disconnect failed
02:08:15.378 4758-4758/? W/View: requestLayout() improperly called by android.view.SurfaceView{808c956 V.E...... ......I. 0,0-0,0} during layout: running second layout pass
02:08:19.986 fhircore.quest W/.fhircore.ques: Throwing OutOfMemoryError "Failed to allocate a 24 byte allocation with 0 free bytes and 0B until OOM, target footprint 201333432, growth limit 201326592" (VmSize 6500136 kB)
02:08:22.352 fhircore.quest W/.fhircore.ques: Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 0 free bytes and 0B until OOM, target footprint 201333432, growth limit 201326592" (VmSize 6500136 kB)
02:08:24.737 4378-4422/? E/Watchdog: !@Sync 11407 [02:08:24.737] FD count : 581, wdog_way : softdog
02:08:25.619 fhircore.quest W/.fhircore.ques: Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 0 free bytes and 0B until OOM, target footprint 201333432, growth limit 201326592" (VmSize 6500136 kB, recursive case)
02:08:25.620 fhircore.quest W/.fhircore.ques: "FinalizerDaemon" daemon prio=5 tid=11 Runnable
02:08:25.620 fhircore.quest W/.fhircore.ques:   | group="system" sCount=0 dsCount=0 flags=0 obj=0x12d89730 self=0x7db48b9c00
02:08:25.620 fhircore.quest W/.fhircore.ques:   | sysTid=446 nice=4 cgrp=default sched=0/0 handle=0x7d24074d50
02:08:25.620 fhircore.quest W/.fhircore.ques:   | state=R schedstat=( 7433183922 670171232 1475 ) utm=701 stm=41 core=7 HZ=100
02:08:25.620 fhircore.quest W/.fhircore.ques:   | stack=0x7d23f72000-0x7d23f74000 stackSize=1039KB
02:08:25.620 fhircore.quest W/.fhircore.ques:   | held mutexes= "mutator lock"(shared held)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:63)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at java.lang.Daemons$Daemon.run(Daemons.java:137)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at java.lang.Thread.run(Thread.java:919)
02:08:25.620 fhircore.quest W/.fhircore.ques: "FinalizerDaemon" daemon prio=5 tid=11 Runnable
02:08:25.620 fhircore.quest W/.fhircore.ques:   | group="system" sCount=0 dsCount=0 flags=0 obj=0x12d89730 self=0x7db48b9c00
02:08:25.620 fhircore.quest W/.fhircore.ques:   | sysTid=446 nice=4 cgrp=default sched=0/0 handle=0x7d24074d50
02:08:25.620 fhircore.quest W/.fhircore.ques:   | state=R schedstat=( 7433183922 670171232 1475 ) utm=701 stm=41 core=7 HZ=100
02:08:25.620 fhircore.quest W/.fhircore.ques:   | stack=0x7d23f72000-0x7d23f74000 stackSize=1039KB
02:08:25.620 fhircore.quest W/.fhircore.ques:   | held mutexes= "mutator lock"(shared held)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at com.android.internal.os.BinderInternal$GcWatcher.finalize(BinderInternal.java:63)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at java.lang.Daemons$Daemon.run(Daemons.java:137)
02:08:25.620 fhircore.quest W/.fhircore.ques:     at java.lang.Thread.run(Thread.java:919)
02:08:25.621 fhircore.quest E/System: Uncaught exception thrown by finalizer
02:08:28.875 431-1475/fhircore.quest W/.fhircore.ques: Throwing OutOfMemoryError "Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 201333432, growth limit 201326592" (VmSize 6500136 kB)
02:08:31.259 431-431/fhircore.quest W/.fhircore.ques: Throwing OutOfMemoryError "Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 201333432, growth limit 201326592" (VmSize 6500136 kB)
02:08:34.513 fhircore.quest W/.fhircore.ques: Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 0 free bytes and 0B until OOM, target footprint 201333432, growth limit 201326592" (VmSize 6500136 kB, recursive case)
02:08:34.514 fhircore.quest W/.fhircore.ques: "DefaultDispatcher-worker-1" daemon prio=5 tid=20 Runnable
02:08:34.514 fhircore.quest W/.fhircore.ques:   | group="main" sCount=0 dsCount=0 flags=0 obj=0x12c83548 self=0x7db4913800
02:08:34.514 fhircore.quest W/.fhircore.ques:   | sysTid=506 nice=0 cgrp=default sched=0/0 handle=0x7cb42c5d50
02:08:34.514 fhircore.quest W/.fhircore.ques:   | state=R schedstat=( 147248344835 7719650583 28457 ) utm=14097 stm=627 core=7 HZ=100
02:08:34.514 fhircore.quest W/.fhircore.ques:   | stack=0x7cb41c3000-0x7cb41c5000 stackSize=1039KB
02:08:34.514 fhircore.quest W/.fhircore.ques:   | held mutexes= "mutator lock"(shared held)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at java.lang.StringBuilder.toString(StringBuilder.java:413)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseType(JsonParser.java:28559)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseElementDefinitionProperties(JsonParser.java:1671)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseElementDefinition(JsonParser.java:1556)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseStructureDefinitionStructureDefinitionSnapshotComponentProperties(JsonParser.java:24308)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseStructureDefinitionStructureDefinitionSnapshotComponent(JsonParser.java:24299)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseStructureDefinitionProperties(JsonParser.java:24248)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseStructureDefinition(JsonParser.java:24112)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseResource(JsonParser.java:28356)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParserBase.parse(JsonParserBase.java:124)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.context.SimpleWorkerContext.loadFromFileJson(SimpleWorkerContext.java:272)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.context.SimpleWorkerContext.loadDefinitionItem(SimpleWorkerContext.java:221)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.context.SimpleWorkerContext.loadFromPackage(SimpleWorkerContext.java:295)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.context.SimpleWorkerContext.fromPackage(SimpleWorkerContext.java:159)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at com.google.android.fhir.datacapture.utilities.SimpleWorkerContextProvider.loadSimpleWorkerContext(SimpleWorkerContextProvider.kt:43)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at fhircore.engine.util.extension.ApplicationExtensionKt.initializeWorkerContext(ApplicationExtension.kt:161)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at fhircore.quest.QuestApplication$initializeWorkerContextProvider$1.invokeSuspend(QuestApplication.kt:123)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
02:08:34.514 fhircore.quest W/.fhircore.ques: "DefaultDispatcher-worker-1" daemon prio=5 tid=20 Runnable
02:08:34.514 fhircore.quest W/.fhircore.ques:   | group="main" sCount=0 dsCount=0 flags=0 obj=0x12c83548 self=0x7db4913800
02:08:34.514 fhircore.quest W/.fhircore.ques:   | sysTid=506 nice=0 cgrp=default sched=0/0 handle=0x7cb42c5d50
02:08:34.514 fhircore.quest W/.fhircore.ques:   | state=R schedstat=( 147248699835 7719650583 28457 ) utm=14097 stm=627 core=7 HZ=100
02:08:34.514 fhircore.quest W/.fhircore.ques:   | stack=0x7cb41c3000-0x7cb41c5000 stackSize=1039KB
02:08:34.514 fhircore.quest W/.fhircore.ques:   | held mutexes= "mutator lock"(shared held)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at java.lang.StringBuilder.toString(StringBuilder.java:413)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseType(JsonParser.java:28559)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseElementDefinitionProperties(JsonParser.java:1671)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseElementDefinition(JsonParser.java:1556)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseStructureDefinitionStructureDefinitionSnapshotComponentProperties(JsonParser.java:24308)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseStructureDefinitionStructureDefinitionSnapshotComponent(JsonParser.java:24299)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseStructureDefinitionProperties(JsonParser.java:24248)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseStructureDefinition(JsonParser.java:24112)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParser.parseResource(JsonParser.java:28356)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.formats.JsonParserBase.parse(JsonParserBase.java:124)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.context.SimpleWorkerContext.loadFromFileJson(SimpleWorkerContext.java:272)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.context.SimpleWorkerContext.loadDefinitionItem(SimpleWorkerContext.java:221)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.context.SimpleWorkerContext.loadFromPackage(SimpleWorkerContext.java:295)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at org.hl7.fhir.r4.context.SimpleWorkerContext.fromPackage(SimpleWorkerContext.java:159)
02:08:34.514 fhircore.quest W/.fhircore.ques:     at com.google.android.fhir.datacapture.utilities.SimpleWorkerContextProvider.loadSimpleWorkerContext(SimpleWorkerContextProvider.kt:43)
02:08:34.515 fhircore.quest W/.fhircore.ques:     at fhircore.engine.util.extension.ApplicationExtensionKt.initializeWorkerContext(ApplicationExtension.kt:161)
02:08:34.515 fhircore.quest W/.fhircore.ques:     at fhircore.quest.QuestApplication$initializeWorkerContextProvider$1.invokeSuspend(QuestApplication.kt:123)
02:08:34.515 fhircore.quest W/.fhircore.ques:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02:08:34.515 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02:08:34.515 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
02:08:34.515 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
02:08:34.515 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
02:08:34.515 fhircore.quest W/.fhircore.ques:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
02:08:35.208 431-1475/fhircore.quest E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 201333432, growth limit 201326592
        at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
        at android.os.Binder.execTransact(Binder.java:1027)
02:08:35.212 431-1475/fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: Binder:431_7
    Process: fhircore.quest, PID: 431
    java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 201333432, growth limit 201326592
        at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
        at android.os.Binder.execTransact(Binder.java:1027)
02:08:35.228 4378-6528/? W/ActivityManager: crash : fhircore.quest,0
02:08:35.231 fhircore.quest E/System: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
02:08:35.232 4378-6528/? W/ActivityTaskManager:   Force finishing activity fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity
02:08:35.354 3426-3721/? W/AppErrorNotification: Skip. fhircore.questis excluded
02:08:35.390 4378-4589/? W/InputDispatcher: channel '4844b88 fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd, fd=631
02:08:35.391 4378-4589/? W/InputDispatcher: channel '70e2095 fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9, fd=626
02:08:35.391 4378-4589/? E/InputDispatcher: channel '70e2095 fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02:08:35.400 4378-6530/? W/InputDispatcher: Attempted to unregister already unregistered input channel '4844b88 fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity (server)'
02:08:35.412 4378-6527/? W/InputDispatcher: Attempted to unregister already unregistered input channel '67e07b9 fhircore.quest/fhircore.quest.ui.patient.register.PatientRegisterActivity (server)'
02:08:35.417 4378-6453/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'c0183af fhircore.quest/fhircore.quest.ui.patient.details.QuestPatientDetailActivity (server)'
02:08:35.421 4378-6445/? W/InputDispatcher: Attempted to unregister already unregistered input channel '70e2095 fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity (server)'
02:08:35.432 4378-4419/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{4844b88 u0 fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity EXITING}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:575)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:813)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3633)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5197)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
02:08:35.439 4378-4407/? E/WindowManager: win=Window{70e2095 u0 fhircore.quest/fhircore.engine.ui.questionnaire.QuestionnaireActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1199 com.android.server.wm.AppWindowToken.destroySurfaces:1180 com.android.server.wm.WindowState.onExitAnimationDone:5030
```

**Comment by ellykits** [comment]
I think we can close this. Issue was fixed with the DI refactor. However there is an OOM exception from MeasureEvaluateTest. We can track that separately.

**Comment by pld** [comment]
Is that still happening? I tried to fix that yesterday by setting the memory in the test profile, maybe that didn't work

**Comment by ellykits** [comment]
The out of memory for `MeasureEvaluatorTest` is  still happening especially
when run locally MeasureEvaluatorTest.kt
<https://github.com/opensrp/fhircore/blob/main/android/engine/src/test/java/org/smartregister/fhircore/engine/cql/MeasureEvaluatorTest.kt>
is
ignored. The test should be refactored to use mocks and the implementation
needs to use DI.

**Comment by pld** [comment]
OK, I think it’s passing now on the CI, with the memory change, https://github.com/opensrp/fhircore/blob/cd3b4787fd89527839a1b9203669d6ca4d146470/android/engine/src/test/java/org/smartregister/fhircore/engine/cql/MeasureEvaluatorTest.kt <https://github.com/opensrp/fhircore/blob/cd3b4787fd89527839a1b9203669d6ca4d146470/android/engine/src/test/java/org/smartregister/fhircore/engine/cql/MeasureEvaluatorTest.kt>

but I agree it should be refactored, the JSON library it loads is very large

**Comment by ellykits** [comment]
I may have ignored it in a branch that was recently merged. Will revert in
a separate PR.

**Comment by pld** [comment]
No it’s ok, I think it’s fine to stay ignored, looks like Maimoona is working on a longer term fix.

We can probably remove the 2 lines I added to set memory in tests
