### ISSUE TITLE
Covax Demo app  - On save vaccine app crashes 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#684]
**Describe the bug**
App crushed on submit vaccine given 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Patient profile
2. Click on Revocrd vaccine
3. Select vaccine option
4. Save
5. Error occurs

**Expected behaviour**
1. On select and save vaccine, the record should be submitted an appropriate response given to the user and returned to an updated profile page 
2. If the first dose, alert next due date for 2nd dose
3. If the second dose, alert full immunised
4. Return to patientprofilr page iwth upfated details  

**Screenshots**
 
**Saving** 
<img src="https://user-images.githubusercontent.com/4540684/139406023-d4073809-20dc-471f-a234-1eed38d0bdd8.png" width="200" height="400" />

**Crush** 
<img src="https://user-images.githubusercontent.com/4540684/139406037-e5e2c145-b6e9-447e-932a-77328da340f2.png" width="200" height="400" />

**Success Path should return either A or B** 
**A. Patient Profile  - 1st Dose + Next due date**
<img src="https://user-images.githubusercontent.com/4540684/139406711-bc436526-a72d-4649-8a97-2d9a2dcb7c9a.png" width="200" height="400" />

**B. Patient Profile  - Immunized**
<img src="https://user-images.githubusercontent.com/4540684/139406710-5b1aaf90-dbef-4530-bbb6-64b93b18ccdf.png" width="200" height="400" />

**Comment by f-odhiambo** [comment]
**Current Test  - Nov 16th 2021**

NB. These tests are based on the latest code merged on the `main branch` running on Android Emulator API 31

1. New Error on Save Vaccine on Emulator
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.smartregister.fhircore.eir/org.smartregister.fhircore.eir.ui.patient.register.PatientRegisterActivity}: kotlin.UninitializedPropertyAccessException: lateinit property applicationConfiguration has not been initialized

 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property applicationConfiguration has not been initialized
        at org.smartregister.fhircore.eir.EirApplication.getApplicationConfiguration(EirApplication.kt:35)
        at org.smartregister.fhircore.engine.ui.register.RegisterViewModel.<init>(RegisterViewModel.kt:64)
        at org.smartregister.fhircore.engine.ui.register.RegisterViewModel.<init>(RegisterViewModel.kt:44)
        at org.smartregister.fhircore.engine.ui.register.BaseRegisterActivity.onCreate(BaseRegisterActivity.kt:132)
        at org.smartregister.fhircore.eir.ui.patient.register.PatientRegisterActivity.onCreate(PatientRegisterActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
```
2. New Error on Save Vaccine on Physical Device 
```
2021-11-15 00:18:20.016 15685-15977/org.smartregister.fhircore.quest E/WM-WorkerFactory: Could not instantiate org.smartregister.fhircore.quest.QuestFhirSyncWorker
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:96)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property applicationConfiguration has not been initialized
        at org.smartregister.fhircore.quest.QuestApplication.getApplicationConfiguration(QuestApplication.kt:42)
        at org.smartregister.fhircore.engine.data.remote.fhir.resource.FhirResourceService$Companion.create(FhirResourceService.kt:74)
        at org.smartregister.fhircore.engine.data.remote.fhir.resource.FhirResourceDataSource$Companion.getInstance(FhirResourceDataSource.kt:70)
        at org.smartregister.fhircore.quest.QuestFhirSyncWorker.getDataSource(QuestFhirSyncWorker.kt:29)
        at org.smartregister.fhircore.quest.QuestFhirSyncWorker.getDataSource(QuestFhirSyncWorker.kt:24)
        at com.google.android.fhir.sync.FhirSyncWorker.<init>(FhirSyncWorker.kt:55)
        at org.smartregister.fhircore.quest.QuestFhirSyncWorker.<init>(QuestFhirSyncWorker.kt:25)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:96) 
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244) 
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136) 
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2021-11-15 00:18:20.017 15685-15977/org.smartregister.fhircore.quest E/WM-WorkerWrapper: Could not create Worker org.smartregister.fhircore.quest.QuestFhirSyncWorker
```

**Comment by maimoonak** [comment]
I tried submitting vaccines form but there was no error in logs and no vaccine was shown as received on Activity, so I ended up repeating it 3/4 times. Then realized that it actually saves the entity but missing details

**Immunization**	{"resourceType":"Immunization","id":"ce6d770c-8f16-4ef5-87eb-31cd71536d63"}

**QuestionnaireResponse**	 {"resourceType":"QuestionnaireResponse","id":"ef2532d3-dec8-4852-b01d-152be51b3918","contained":[{"resourceType":"Immunization","id":"ce6d770c-8f16-4ef5-87eb-31cd71536d63"}],"questionnaire":"Questionnaire/800","subject":{"reference":"Immunization/e91f12be-6c54-46c0-87c9-09103c24f782"},"authored":"2021-11-22T14:31:31+05:00","item":[{"linkId":"Record-Vaccine","answer":[{"valueCoding":{"code":"**Moderna**"}}]}]}

**Comment by maimoonak** [comment]
Same (above) is true for a completely newly registered patient

**Comment by maimoonak** [comment]
Ok. So the issue is

`handleQuestionnaireResponse(questionnaireResponse, editMode)`
 in QuestionnaireActivity. The method 

`handleQuestionnaireResponse(questionnaireResponse)`

was open and overridden in other activities in covax and anc but it has been replaced by a new method without handling the overridden method in other apps. This led to the custom implementation never being called and hence does not save the data as expected by overridden method
