### ISSUE TITLE
Quest/G6PD  - Test CQL statement on CQLEvaluator module and document findings

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#731]
- [x] Check out the implementation of the CQLEvaluatorSample app and see if we can tweak the Library of resources to suit our use case 
- [x] Document the findings of the RnD
- [x] Modify the library of resources to mimic the G6PD use case 
- [x] Run and test the  CQL statement  for G6PD Threshold management

**Comment by maimoonak** [comment]
App which runs library throws OutOfMemory exception due to the fact that it tried to load 54 MB file

2021-11-08 15:56:12.370 18516-18516/org.opencds.cqf.cql.evaluator.android.sample W/.android.sampl: Throwing OutOfMemoryError "Failed to allocate a 25606512 byte allocation with 12540120 free bytes and 11MB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 5587048 kB)
2021-11-08 15:56:13.211 18516-18516/org.opencds.cqf.cql.evaluator.android.sample W/.android.sampl: Throwing OutOfMemoryError "Failed to allocate a 25606512 byte allocation with 12540072 free bytes and 11MB until OOM, target footprint 201326592, growth limit 201326592" (VmSize 5587048 kB)
2021-11-08 15:56:13.215 18516-18516/org.opencds.cqf.cql.evaluator.android.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.opencds.cqf.cql.evaluator.android.sample, PID: 18516
    java.lang.OutOfMemoryError: Failed to allocate a 25606512 byte allocation with 12540072 free bytes and 11MB until OOM, target footprint 201326592, growth limit 201326592
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
        at java.lang.StringBuilder.toString(StringBuilder.java:413)
        at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:465)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:301)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:286)
......
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4635)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3032)
........
        at ca.uhn.fhir.parser.BaseParser.parseResource(BaseParser.java:583)
        at org.opencds.cqf.cql.evaluator.android.sample.AssetBundler.parseFile(AssetBundler.java:118)
......
        at org.opencds.cqf.cql.evaluator.android.sample.AssetBundler.getContentBundle(AssetBundler.java:34)
        at org.opencds.cqf.cql.evaluator.android.sample.LibraryActivity.onCreate(LibraryActivity.java:71)

**Comment by maimoonak** [comment]
The code was modified and setup by Davison and he had setup the CQL for Measure. Looks like he was using elm instead of CQL which is giving stackoverflow and sometimes JAXB exceptions as it tries to convert cql-elm it automatically internally..

Setting up https://github.com/cqframework/cql-translation-service and trying to use translated content to skip the step

**Comment by maimoonak** [comment]
I have tried almost everything, from changing different scripts to using own implementation of some xml parsin logic, using other xml libs, but all three options

JSON -> giving that 'type' error
XML -> giving some xml parsing issue with AccessModifier
CQL -> Stackoverflow error

Would once again from start but rightnow looks like I have almost given up

**Comment by maimoonak** [comment]
The issue with [translation-service ](https://github.com/cqframework/cql-translation-service) was that it does not generate type for all objects. Which was leading to issue with recognizing the correct evaluator for given object.

The service uses the latest translator and generates correct structure as mentioned acceptable in [service](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/src/test/resources/org/cqframework/cql/cql2elm/CMS146v2_Expected.json) itself

Handling the deserialization error with assigning correct class resolved the issue with recognizing the properties

**Comment by maimoonak** [comment]
Findings and Caveats:

- CQL Evaluator app not working and it leads to OutOfMemory issues
- @kimigxfoxy  had done a good work to pick code, modify it and allow running Library against evaluator
- **The CQL evaluator allows 3 types of script content elm+json, elm+xml, cql) and only application/elm+json is working,** other two leads to internal conversions to xml which occalsionally causes StackOverflow, Or OutOfMemory and on succcessful run leads to JAXB Exception for xml conversion. 
- Adding eclipse.persistence for xml conversion library causes following
```
org.opencds.cqf.cql.engine.exception.CqlException: Translation of library G6PD-RIM failed with the following message: javax.xml.bind.JAXBException: can't load this type of class file
     - with linked exception:
    [java.lang.UnsupportedOperationException: can't load this type of class file]
        at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.translate(TranslatingLibraryLoader.java:153)
        at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.load(TranslatingLibraryLoader.java:88)
        at org.opencds.cqf.cql.engine.execution.CqlEngine.loadAndValidate(CqlEngine.java:254)
```

**Working conditions**
- So, so far application/elm+json is the only option
- Latest [translation-service ](https://github.com/cqframework/cql-translation-service) does not generate 'type' for all objects, so a fix was required to make it automatically picks class resolvers for types for that json object. The JsonCqlLibraryReader was replaces by custom handling of missing property
- Library version match is very very important. The version should match in encoded script and the FHIR Library REsource as well
- CQL code does not handle exceptions correctly and sometimes just catches without any logs. The TranslatingLibraryLoader was overridden to override method and catch and log exceptions to understand the real causes
- CQL and StructureMap use alot of memory and using both at a time when app is starting leads to crashes and OutOfMEmory issues
- CQL script should produce FHIR output instead of statements to enure that feature is generic

**Next Steps**
- Deploy translation service so that others can use
- Make code use library from DB, sync required and dependent libraries correctly, log exceptions and errors correctly
- Add a feature and wiki that guides and parses the CQL in a generic way and saves the produced entities into DB
- Test against different scripts to figure out missing pieces

**Comment by maimoonak** [comment]
The PR is submitted the shows the changes done

- Rightnow it uses hardcoded library links, we need a way to use libraries dynamically for feature
- It does not work in parallel with StructureMap, if app is started then wait for 3 mins before starting otherwise OutOfMemory issues are seen (not exists in apk shared with Francis as code commented out there)
- To make changes to library do following 
- - Update and test CQL script (use vesion 4.0.1 only fo fhir-helper, and do not update the library version anywhere)
- - Translate using [translation-service](https://github.com/cqframework/cql-translation-service)
- - Encode json using https://www.base64encode.org/
- - PUT (rest) the library 4575 and modify the content with encoded data
- - Sync app again and test changes after successful sync

**Comment by f-odhiambo** [comment]
Marking this as DONE
