### ISSUE TITLE
Quest v0.2 / G6PD : Crash after capturing a photo

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#833]
**Describe the bug**
On some devices, the quest app will crash after capturing a photo because of `TransactionTooLarge` exception.
As for why it happens **only** on some devices is not clear yet.
Tested on this devices:
- Pixel 4 API 30 [WORK]
- Pixel 4a API 30 [WORK]
- Pixel 4a API 31 [CRASH]
- Xiaomi Pocophone API 28 [CRASH]
- Nexus 5X API 28 [CRASH]

**To Reproduce**
1. Go to Quest app
2. Login
3. Click on one of the clients
4. Click on 'G6PD TEST PHOTO RESULT'
5. Click 'Number' on 'G6PD Result Type'
6. Click 'Take Photo'
7. Click the camera button in camera app (Capturing a photo)
8. Click the check button in camera app (Saving a photo)
9. Quest app crash

**Expected behavior**
After taking and saving a photo, it should return from camera app to quest app
Screenshot from Pixel 4a API 30:
<img src="https://user-images.githubusercontent.com/62053304/144819394-5b90dac3-3e71-4db2-99c1-fcb1bd8da5b2.png" width="256"/>

**Screenshots**
Screenshot from Pixel 4a API 31:
<img src="https://user-images.githubusercontent.com/62053304/144815619-fe805b64-531e-467b-a243-d2a7f0cb4557.png" width="256"/>
<img src="https://user-images.githubusercontent.com/62053304/144815628-e2d32801-0362-40c5-b80a-2b9f916783b8.png" width="256"/>
<img src="https://user-images.githubusercontent.com/62053304/144815632-1ed350e7-50e3-4dfa-b9b9-8cf4e088a856.png" width="256"/>
<img src="https://user-images.githubusercontent.com/62053304/144815616-00a0eb89-35e5-4aa6-a94b-315423e8a41d.png" width="256"/>
<img src="https://user-images.githubusercontent.com/62053304/144815604-613b1f89-d8bc-47cf-b781-2eb6893e70d4.png" width="256"/>

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 12
 - Version 31

**Additional context**
```
2021-12-06 12:36:16.396 6963-6963/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 6963
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 660344 bytes
        at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.TransactionTooLargeException: data parcel size 660344 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:571)
        at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1297)
        at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
2021-12-06 12:36:17.637 395-395/? E/BpTransactionCompletedListener: Failed to transact (-32)
```

**Comment by FikriMilano** [comment]
The issue seems to happen because the outState bundle was more than 1MB.
I tried to clear that and the crash no longer happens. Tested on Pixel 4a API 31.
Will try to test that on several devices from API 21 to 31 and see if there’s any drawbacks using that solution.

cc @f-odhiambo

**Comment by FikriMilano** [comment]
The issue seems to happen because the outState bundle was more than 1MB.
I tried to clear that and the crash no longer happens. Tested on Pixel 4a API 31.

Will test that on several devices from API 21 to 31 and see if there’s any drawbacks using that solution.

cc @f-odhiambo

**Comment by FikriMilano** [comment]
I tried to test this on emulator with API 21 to 23 but it always failed to install. It's Probably because of the emulator, also tried to troubleshoot but still failed to install, so will skip those for now.

But for API 24 to 31, this solution works just fine. Will proceed with the PR.
