### ISSUE TITLE
CHW/ANC  - Issue adding a new Family on ANC 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#860]
**Describe the bug**
Add family not working in ANC app correctly  seems to be an issue with Out of memory and also leaked window 

**To Reproduce**
Steps to reproduce the behaviour:

1. Clear all cache or do a clean install of the app 
2. Go to ANC app 
3. Click on Add Family
4. Add a family and press save 
5. See screenshots

**Expected behaviour**
1. Go to Family 
2. Click on Add Family
3. Add a family and press save 
4. Try to find the new Family in the Family register 
4. Retrieve the family via search or scrolling  on the paginated Family list

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device:Emulator
 - Android version: 12
 - Version  : API 29

**Additional context**
N/A

**Logcat** 
`2021-12-10 17:25:52.129 2060-3826/system_process E/InputDispatcher: Window handle Window{d2c140 u0 org.smartregister.fhircore.anc/org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity} has no registered input channel`

**More logs** 

```
2022-01-03 16:59:31.418 2750-2750/org.smartregister.fhircore.anc E/WindowManager: android.view.WindowLeaked: Activity org.smartregister.fhircore.anc.ui.family.form.FamilyQuestionnaireActivity has leaked window DecorView@19424b2[FamilyQuestionnaireActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:783)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:767)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:389)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
        at android.app.Dialog.show(Dialog.java:345)
        at android.app.AlertDialog$Builder.show(AlertDialog.java:1131)
        at org.smartregister.fhircore.engine.ui.base.AlertDialogue.showAlert(AlertDialogue.kt:83)
        at org.smartregister.fhircore.engine.ui.base.AlertDialogue.showAlert$default(AlertDialogue.kt:56)
        at org.smartregister.fhircore.engine.ui.base.AlertDialogue.showProgressAlert(AlertDialogue.kt:142)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity.handleQuestionnaireSubmit(QuestionnaireActivity.kt:228)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity$onClick$1.invoke(QuestionnaireActivity.kt:205)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity$onClick$1.invoke(QuestionnaireActivity.kt:205)
        at org.smartregister.fhircore.engine.ui.base.AlertDialogue.showAlert$lambda-7$lambda-4$lambda-3(AlertDialogue.kt:79)
        at org.smartregister.fhircore.engine.ui.base.AlertDialogue.$r8$lambda$cvLf6CgtkFWn06NT-8e1cRYrVTQ(Unknown Source:0)
        at org.smartregister.fhircore.engine.ui.base.AlertDialogue$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:175)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Screenshots**
<img src="https://user-images.githubusercontent.com/4540684/147939607-db9cc2be-d2cb-4913-8a18-33936b118a57.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/4540684/147939592-09faa994-32ef-4a3a-9095-92f260ce9f49.png" width="200" height="400" />

**Comment by f-odhiambo** [comment]
**_PS._** This issue may be blocked by a decision on how we add a Family and how we represent a family using FHIR . More details here https://github.com/opensrp/fhircore/discussions/824

**Comment by pld** [comment]
Hmm maybe, but seems reasonable to fix this error for now regardless of how we change family rep

**Comment by pld** [comment]
that is to say, I'm ok w/this not being blocked in order to resolve the error

**Comment by f-odhiambo** [comment]
Issue seems to be resolved in the latest codebase in `main`
