### ISSUE TITLE
Quest - App crashes when open "G6PD Test Photo Result" Questionnaire Response

### ISSUE THREAD

**Issue by shoaibmushtaq25** [opensrp/fhircore#864]
**Describe the bug**
Quest - App crashes when open "G6PD Test Photo Result" Questionnaire Response

**To Reproduce**
1. Go to 'Search screen' where we enlist the patients
2. Click on 'Aaa Nexus, 5y 1m'
3. Scroll down to 'Responses' section 
4. Cilck on 'G6PD Test Photo Result(13-Dec-2021)'

**Expected behavior**
When we click on `G6PD Test Photo Result(13-Dec-2021)', it should load respective QuestionnaireResponse with no crash

**Screenshots**
<img src="https://user-images.githubusercontent.com/12672919/145817537-dcb2b8b0-b316-4516-847d-b518f215852b.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/12672919/145817618-4fdedd7b-0838-4526-bf70-f5a327cf9334.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/12672919/145816535-19c17f3e-3203-4739-a032-f286f86bcc29.png" width="200" height="400" />

**Smartphone (please complete the following information):**
 - Device: Pixel 3 API 30 emulator
 - Android version: 11
 - Build number: RSR1.201013.001
 - Version: 30

**Additional context**
Stack trace of the crash is here,
        
        `java.lang.RuntimeException: Unable to start activity ComponentInfo{org.smartregister.fhircore.quest/org.smartregister.fhircore.quest.ui.patient.register.PatientRegisterActivity}: kotlin.UninitializedPropertyAccessException: lateinit property appId has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property appId has not been initialized
        at org.smartregister.fhircore.engine.configuration.ConfigurationRegistry.getAppId(ConfigurationRegistry.kt:51)
        at org.smartregister.fhircore.engine.configuration.ConfigurationRegistry.workflowPointName(ConfigurationRegistry.kt:145)
        at org.smartregister.fhircore.engine.ui.register.RegisterViewModel.<init>(RegisterViewModel.kt:137)
        at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$ViewModelCImpl.registerViewModel(DaggerQuestApplication_HiltComponents_SingletonC.java:748)
        at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$ViewModelCImpl.access$2900(DaggerQuestApplication_HiltComponents_SingletonC.java:695)
        at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerQuestApplication_HiltComponents_SingletonC.java:804)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:100)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:109)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at org.smartregister.fhircore.engine.ui.register.BaseRegisterActivity.getRegisterViewModel(BaseRegisterActivity.kt:111)
        at org.smartregister.fhircore.engine.ui.register.BaseRegisterActivity.runSync(BaseRegisterActivity.kt:438)
        at org.smartregister.fhircore.engine.sync.SyncBroadcaster.registerSyncInitiator(SyncHandlers.kt:56)
        at org.smartregister.fhircore.engine.ui.register.BaseRegisterActivity.onCreate(BaseRegisterActivity.kt:137)
        at org.smartregister.fhircore.quest.ui.patient.register.PatientRegisterActivity.onCreate(PatientRegisterActivity.kt:40)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

**Comment by pld** [comment]
Good catch, let's write a test to reproduce and fix

**Comment by FikriMilano** [comment]
@shoaibmushtaq25 
I tried to replicate this and got an additional error log, hope it helps.
```
2021-12-15 21:35:09.260 2577-2577/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 2577
    kotlin.NotImplementedError: Question type ATTACHMENT not supported.
        at com.google.android.fhir.datacapture.QuestionnaireItemAdapter.getItemViewTypeMapping$datacapture_release(QuestionnaireItemAdapter.kt:129)
        at com.google.android.fhir.datacapture.QuestionnaireItemAdapter.getItemViewType(QuestionnaireItemAdapter.kt:104)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6367)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
        at android.view.View.measure(View.java:25466)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:733)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:733)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
2021-12-15 21:35:09.265 2577-2577/org.smartregister.fhircore.quest E/AndroidRuntime:     at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3397)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2228)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by shoaibmushtaq25** [comment]
My observations on this issue are that we are getting appId of ConfigurationRegistery as null very randomly, sometime we get the correct appId and sometime we get it null,
and When we get the correct appId value, we get some error around QuestionnaireType ATTACHMENT not supported, which is missing/pending implementation on Android FHIR SDK side. @FikriMilano

**Comment by FikriMilano** [comment]
Yeah, will investigate more into that

**Comment by ellykits** [comment]
@shoaibmushtaq25 The logs shared by @FikriMilano represent the actual bug causing the app crash. The other logs that @shoaibmushtaq25  shared are produced as result of the emulator attempting to restart the failed Activity before loading the application configurations which will never happen in production. But we may need to add some checks to prevent that from happening. The application configurations are populated after login.

**Comment by FikriMilano** [comment]
Here's my conclusion why this issue happens.
When viewing questionnaire response, it turns out the questionnaire extension that will identify photo capture is missing. Not sure why.
The missing part:
```
"extension":[
   {
      "url":"http://doc-of-photo-capture",
      "valueString":"photo-capture"
   }
]
```

But this won't happen in the same questionnaire when submitting a new response.

For comparison https://turn-fhir.smartregister.org/fhir/Questionnaire/3440/_history/31
And here's the questionnaire log from Android: (when viewing questionnaire response)
```
{
   "resourceType":"Questionnaire",
   "id":"3440",
   "meta":{
      "versionId":"31",
      "lastUpdated":"2021-12-14T00:32:08.720+00:00",
      "source":"#161c3d17c58686e0"
   },
   "language":"en",
   "extension":[
      {
         "url":"http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-targetStructureMap",
         "valueCanonical":"https://fhir.labs.smartregister.org/StructureMap/5875"
      }
   ],
   "name":"G6PD Test Photo Result",
   "title":"G6PD Test Photo Result",
   "status":"active",
   "subjectType":[
      "Patient"
   ],
   "publisher":"ONA",
   "useContext":[
      {
         "code":{
            "system":"http://hl7.org/fhir/codesystem-usage-context-type.html",
            "code":"focus"
         },
         "valueCodeableConcept":{
            "coding":[
               {
                  "system":"http://fhir.ona.io",
                  "code":"000002",
                  "display":"G6PD Test Photo Results"
               }
            ]
         }
      }
   ],
   "item":[
      {
         "extension":[
            {
               "url":"http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression",
               "valueExpression":{
                  "language":"text/fhirpath",
                  "expression":"QuestionnaireResponse.item.where(linkId = 'result_capture_image').answer.value"
               }
            }
         ],
         "linkId":"result_capture_image",
         "text":"Add instructions for capturing G6PD test information",
         "type":"display",
         "readOnly":true
      },
      {
         "extension":[
            {
               "url":"http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression",
               "valueExpression":{
                  "language":"text/fhirpath",
                  "expression":"QuestionnaireResponse.item.where(linkId = 'result_type').answer.value"
               }
            }
         ],
         "linkId":"result_type",
         "code":[
            {
               "system":"http://fhir.ona.io",
               "code":"000001",
               "display":"G6PD Result Type"
            }
         ],
         "text":"G6PD Result Type",
         "type":"choice",
         "required":true,
         "readOnly":true,
         "answerOption":[
            {
               "valueCoding":{
                  "system":"https://www.snomed.org",
                  "code":"410680006",
                  "display":"Number"
               }
            },
            {
               "valueCoding":{
                  "system":"https://www.snomed.org",
                  "code":"405358009",
                  "display":"Error"
               }
            },
            {
               "valueCoding":{
                  "system":"https://www.snomed.org",
                  "code":"385432009",
                  "display":"N/A"
               }
            }
         ]
      },
      {
         "extension":[
            {
               "url":"http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression",
               "valueExpression":{
                  "language":"text/fhirpath",
                  "expression":"QuestionnaireResponse.item.where(linkId = 'haemoglobin_level').answer.value"
               }
            }
         ],
         "linkId":"haemoglobin_level",
         "code":[
            {
               "system":"https://www.snomed.org",
               "code":"104142005",
               "display":"Plasma haemoglobin level"
            }
         ],
         "text":"Hemoglobin Levels",
         "type":"choice",
         "enableWhen":[
            {
               "question":"result_type",
               "operator":"=",
               "answerCoding":{
                  "system":"https://www.snomed.org",
                  "code":"385432009"
               }
            }
         ],
         "readOnly":true,
         "answerOption":[
            {
               "valueCoding":{
                  "system":"https://www.snomed.org",
                  "code":"75540009",
                  "display":"High"
               }
            },
            {
               "valueCoding":{
                  "system":"https://www.snomed.org",
                  "code":"62482003",
                  "display":"Low"
               }
            }
         ]
      },
      {
         "extension":[
            {
               "url":"http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression",
               "valueExpression":{
                  "language":"text/fhirpath",
                  "expression":"QuestionnaireResponse.item.where(linkId = 'g6pd').answer.value"
               }
            }
         ],
         "linkId":"g6pd",
         "code":[
            {
               "system":"http://snomed.info/sct",
               "code":"86859003",
               "display":"G6PD Enzyme"
            }
         ],
         "text":"G6PD",
         "type":"decimal",
         "enableWhen":[
            {
               "question":"result_type",
               "operator":"=",
               "answerCoding":{
                  "system":"https://www.snomed.org",
                  "code":"410680006"
               }
            },
            {
               "question":"result_type",
               "operator":"=",
               "answerCoding":{
                  "system":"https://www.snomed.org",
                  "code":"385432009"
               }
            }
         ],
         "enableBehavior":"any",
         "required":true,
         "readOnly":true
      },
      {
         "extension":[
            {
               "url":"http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression",
               "valueExpression":{
                  "language":"text/fhirpath",
                  "expression":"QuestionnaireResponse.item.where(linkId = 'haemoglobin').answer.value"
               }
            }
         ],
         "linkId":"haemoglobin",
         "code":[
            {
               "system":"http://snomed.info/sct",
               "code":"259695003",
               "display":"Hemoglobin"
            }
         ],
         "text":"Hemoglobin (Hb)",
         "type":"decimal",
         "enableWhen":[
            {
               "question":"result_type",
               "operator":"=",
               "answerCoding":{
                  "system":"https://www.snomed.org",
                  "code":"410680006"
               }
            },
            {
               "question":"result_type",
               "operator":"=",
               "answerCoding":{
                  "system":"https://www.snomed.org",
                  "code":"385432009"
               }
            }
         ],
         "enableBehavior":"any",
         "required":true,
         "readOnly":true
      },
      {
         "extension":[
            {
               "url":"http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression",
               "valueExpression":{
                  "language":"text/fhirpath",
                  "expression":"QuestionnaireResponse.item.where(linkId = 'photo').answer.value"
               }
            }
         ],
         "linkId":"photo",
         "text":"Photo of device",
         "type":"attachment",
         "enableWhen":[
            {
               "question":"result_type",
               "operator":"=",
               "answerCoding":{
                  "system":"https://www.snomed.org",
                  "code":"410680006"
               }
            },
            {
               "question":"result_type",
               "operator":"=",
               "answerCoding":{
                  "system":"https://www.snomed.org",
                  "code":"385432009"
               }
            }
         ],
         "enableBehavior":"any",
         "readOnly":true
      }
   ]
}
```

**Comment by FikriMilano** [comment]
Main problem founded.
It turns out there is a method in the code base that overwrites the extension of each questionnaire item when viewing it’s response.
https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/util/extension/ResourceExtension.kt#L97-L128

A PR is on the way.
