### ISSUE TITLE
Quest : Patient registration with estimated age/dob not working

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#876]
**Describe the bug**
On the quest app, one cannot successfully  register a patient 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Quest app
2. Click on Register new client 
3. Complete registration survey 
4. User not saved

**Expected behaviour**
1. On successfully save, I should be able to either view the client on the patient list or search and retrieve the user 

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 12
 - Build number:SP1A.211105.002

**Additional context**

1. Update the registration questionnaire to have Date of birth selection default to date selection

**Comment by ellykits** [comment]
Found the error. Issue happens when the user opts to provide the age of the client instead of the actual DOB date:

```
2021-12-20 17:12:19.512 8086-8086/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 8086
    org.hl7.fhir.exceptions.FHIRException: Exception executing transform patient.birthDate = evaluate(item_age"today() - $this.answer.value") on Rule "r_p_age": Error performing -: left and right operand have incompatible or illegal types (date, decimal) (@char 3)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.runTransform(StructureMapUtilities.java:1958)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.processTarget(StructureMapUtilities.java:1829)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1416)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1420)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1403)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeDependency(StructureMapUtilities.java:1462)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1424)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1403)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.transform(StructureMapUtilities.java:1377)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractByStructureMap(ResourceMapper.kt:172)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.access$extractByStructureMap(ResourceMapper.kt:77)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper$extractByStructureMap$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: org.hl7.fhir.exceptions.PathEngineException: Error performing -: left and right operand have incompatible or illegal types (date, decimal) (@char 3)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.opMinus(FHIRPathEngine.java:2236)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.operate(FHIRPathEngine.java:1432)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.execute(FHIRPathEngine.java:1189)
        at org.hl7.fhir.r4.utils.FHIRPathEngine.evaluate(FHIRPathEngine.java:542)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.runTransform(StructureMapUtilities.java:1888)
        at org.hl7.fhir.r4.utils.StructureMapUtilities.processTarget(StructureMapUtilities.java:1829) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1416) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1420) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1403) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeDependency(StructureMapUtilities.java:1462) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeRule(StructureMapUtilities.java:1424) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.executeGroup(StructureMapUtilities.java:1403) 
        at org.hl7.fhir.r4.utils.StructureMapUtilities.transform(StructureMapUtilities.java:1377) 
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extractByStructureMap(ResourceMapper.kt:172) 
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.access$extractByStructureMap(ResourceMapper.kt:77) 
        at com.google.android.fhir.datacapture.mapping.ResourceMapper$extractByStructureMap$1.invokeSuspend(Unknown Source:18) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 


```

**Comment by ekigamba** [comment]
Thanks @ellykits  for the accurate description of the bug and replication. We should aim to have an accurate description and steps of replication for faster solution and clearer continued usage of the feature(s)

**Comment by ekigamba** [comment]
This is a regression bug and was implemented in commit https://github.com/opensrp/fhircore/commit/ff6610fbc9d2e917dadb2639dfb6194581f360a9 for issues
- https://github.com/opensrp/fhircore/issues/652
- https://github.com/opensrp/fhircore/issues/816

Code removing this seems to be in commit 36aec71186c6264fce425e8ad9cf0581c2ce0600 and PR https://github.com/opensrp/fhircore/pull/870

**Comment by ekigamba** [comment]
The java implementations were switched with a StructureMap implementation [here](https://github.com/opensrp/fhircore/pull/865) but it seems that this was not tested here
