### ISSUE TITLE
Quest patient registration crash caused by CQF library functionality

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#919]
**Describe the bug**
The app crashes after patient registration. However, the patient is still recorded with the correct details eg. age converted to dob (not sure what effect the crash has)

**To Reproduce**
1. Run Quest and login using the `demo` account
2. Click on the **Add New Client** button in the clients page
2. Fill in the form with all the patient details
3. Click save
4. The app crashes

**Expected behavior**
The page should close after saving and return to the clients page. The new patient should be immediately available through search or on the correct page number based on alphabetical order

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Emulator Google Pixel 2
 - Android version: Android 11
 - Build number: [e.g. Settings -> About phone -> Build number]
 - Version [e.g. 24]

**Additional context**

Crash logs
```
2022-01-03 10:27:19.129 184-184/? A/libc: crash_dump helper failed to exec
2022-01-03 10:27:19.862 9590-9590/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 9590
    java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at org.smartregister.fhircore.engine.util.extension.QuestionnaireExtensionKt.cqfLibraryId(QuestionnaireExtension.kt:95)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireViewModel$extractAndSaveResources$1.invokeSuspend(QuestionnaireViewModel.kt:192)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2022-01-03 10:27:22.317 509-9929/? E/ActivityManager: ANR in org.smartregister.fhircore.quest (org.smartregister.fhircore.quest/org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity)
    PID: 9590
    Reason: Input dispatching timed out (98187b2 org.smartregister.fhircore.quest/org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity (server) is not responding. Waited 5003ms for FocusEvent(hasFocus=false))
    Parent: org.smartregister.fhircore.quest/org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity
    Load: 1.44 / 1.41 / 1.76
    ----- Output from /proc/pressure/memory -----
    some avg10=0.27 avg60=0.18 avg300=0.29 total=14311055
    full avg10=0.01 avg60=0.04 avg300=0.05 total=3901393
    ----- End output from /proc/pressure/memory -----
```

Crash started happening after merging this commit https://github.com/opensrp/fhircore/commit/a7e511bd4cf2f234dbe9847f4df22981341f0aab on an umerged PR.

**Comment by ekigamba** [comment]
This was reported in this PR https://github.com/opensrp/fhircore/pull/909#issuecomment-1003915228

**Comment by f-odhiambo** [comment]
This issue seems to be fixed from another PR as we can no longer reproduce it. We can create a new ticket if it re-occurs
