### ISSUE TITLE
Quest app crashing due to missing form name 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#935]
**Describe the bug**
Application seem to be crushing due to a missing property on the Quest app 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the Quest app and let it sync all the resources 
2. Click on a patient listed in the Patient List view  
3. App crushes 

**Expected behaviour**

1. Go to the Quest app and let it sync all the resources 
2. Click on a patient listed in the Patient List view  
3. View Loaded questionnaires with either Ona, MSF, G6PD , CODA publisher tag 

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Physical device or Emulator 

**Additional context**

**Function in-app** 
```
suspend fun fetchTestForms(
    filter: SearchFilter,
    appId: String = "quest"
  ): List<QuestionnaireConfig> =
    withContext(dispatcherProvider.io()) {
      val result =
        fhirEngine.search<Questionnaire> {
          filter(
            Questionnaire.CONTEXT,
            CodeableConcept().apply {
              addCoding().apply {
                this.code = filter.code
                this.system = filter.system
              }
            }
          )
        }

      result.map {
        QuestionnaireConfig(
          appId = appId,
          form = it.name,
          title = it.title,
          identifier = it.logicalId
        )
      }
    }
```

**Logcat report** 
```
    --------- beginning of crash
2022-01-07 13:07:49.973 10282-10282/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 10282
    java.lang.NullPointerException: it.name must not be null
        at org.smartregister.fhircore.quest.data.patient.PatientRepository$fetchTestForms$2.invokeSuspend(PatientRepository.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-01-07 13:07:49.983 10282-10282/org.smartregister.fhircore.quest I/Process: Sending signal. PID: 10282 SIG: 9
```

**Comment by f-odhiambo** [comment]
Also noted that there are hardcoded strings i.e.  appId: String = "quest" perhaps that could move to a config file somewhere

**Comment by f-odhiambo** [comment]
Seems like will also need some null pointer exception handling for Questionnaire properties such as 
- Name
- Description 
- TItlte 
And perhaps tweak/ change the code  = q.name to q.name?:"" etc for the remaining fields
