### ISSUE TITLE
Application is crashing if not all questions are being answered

### ISSUE THREAD

**Issue by MuhammadSalman-7214** [opensrp/fhircore#95]
Here is the stack trace of the crash:

```
java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
        at com.google.android.fhir.datacapture.mapping.ResourceMapper.extract(ResourceMapper.kt:105)
        at org.smartregister.fhircore.activity.QuestionnaireActivity.savePatientResource(QuestionnaireActivity.kt:87)
        at org.smartregister.fhircore.activity.QuestionnaireActivity.onOptionsItemSelected(QuestionnaireActivity.kt:70)
        at android.app.Activity.onMenuItemSelected(Activity.java:4137)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at com.android.tools.profiler.support.event.WindowProfilerCallback.onMenuItemSelected(WindowProfilerCallback.java:125)
        at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1176)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by ekigamba** [comment]
New bug when the patient's telephone number is not entered

```
2021-04-27 15:17:07.962 5135-5135/org.smartregister.fhircore E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore, PID: 5135
    java.lang.NullPointerException: patient.telecom[0].value must not be null
        at org.smartregister.fhircore.data.SamplePatients.createPatientItem(SamplePatients.kt:81)
        at org.smartregister.fhircore.data.SamplePatients.getPatientItems(SamplePatients.kt:66)
        at org.smartregister.fhircore.viewmodel.PatientListViewModel$getSearchResults$1.invokeSuspend(PatientListViewModel.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:342)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at org.smartregister.fhircore.viewmodel.PatientListViewModel.getSearchResults(PatientListViewModel.kt:63)
        at org.smartregister.fhircore.viewmodel.PatientListViewModel.getSearchResults$default(PatientListViewModel.kt:62)
        at org.smartregister.fhircore.activity.PatientListActivity.onCreate(PatientListActivity.kt:79)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

This is a crash caused by the sample register not handling nulls

**Comment by ekigamba** [comment]
This was fixed  in https://github.com/google/android-fhir/commit/f0c9fb45a12ad7da1a9a42aebc47c44171a5fe92 and https://github.com/opensrp/fhircore/pull/104
