### ISSUE TITLE
Quest v0.2 / G6PD : App crashes when  G6PD Test Questionnaire is completed  and submitted with a photo attachment

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#974]
**Describe the bug**
App crashes when  G6PD Test Questionnaire is completed  and submitted with a photo attachment

**To Reproduce**
1. Go to the G6PD test 
2. Complete the survey and add a photo/replace photo
3. Submit a completed test 

**Expected behavior**
1. Complete questionnaire with photo and submit with no crash 
2. User should be able to update photo before submission and post with no crash 

**Screenshots**
See video  - TBD

**Smartphone (please complete the following information):**
 - Device: Pixel 4a 
 - Android version: 12
 - Build number: SQ1A.220105.002

**Additional context**
- Photo takes a few seconds before showing up in its placeholder, similar when the photo is updated

> @f-odhiambo Is this a real device? Does this happens in emulator too? with the same device and API version

**Comment by FikriMilano** [comment]
@f-odhiambo Is this a real device?
Does this happens in emulator too? with the same device and API version

**Comment by f-odhiambo** [comment]
> @f-odhiambo Is this a real device? Does this happen in emulators too? with the same device and API version 

Real Devic. See video

https://user-images.githubusercontent.com/4540684/150502386-9e52ec6e-03b4-4aa0-8b8d-06cce138ce99.mp4

**Comment by FikriMilano** [comment]
Error log:
```
2022-01-24 11:09:00.787 8977-8977/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 8977
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.smartregister.fhircore.quest/org.smartregister.fhircore.quest.ui.patient.details.QuestPatientDetailActivity}: kotlin.UninitializedPropertyAccessException: lateinit property appId has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3016)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1716)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property appId has not been initialized
        at org.smartregister.fhircore.engine.configuration.ConfigurationRegistry.getAppId(ConfigurationRegistry.kt:51)
        at org.smartregister.fhircore.engine.configuration.ConfigurationRegistry.workflowPointName(ConfigurationRegistry.kt:145)
        at org.smartregister.fhircore.quest.ui.patient.details.QuestPatientDetailActivity.onCreate(QuestPatientDetailActivity.kt:216)
        at android.app.Activity.performCreate(Activity.java:6974)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2904)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3016) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1716) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:232) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
2022-01-24 11:09:01.318 9006-9006/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 9006
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.smartregister.fhircore.quest/org.smartregister.fhircore.quest.ui.patient.register.PatientRegisterActivity}: kotlin.UninitializedPropertyAccessException: lateinit property appId has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3016)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1716)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property appId has not been initialized
        at org.smartregister.fhircore.engine.configuration.ConfigurationRegistry.getAppId(ConfigurationRegistry.kt:51)
        at org.smartregister.fhircore.engine.configuration.ConfigurationRegistry.workflowPointName(ConfigurationRegistry.kt:145)
        at org.smartregister.fhircore.engine.ui.register.RegisterViewModel.<init>(RegisterViewModel.kt:153)
        at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$ViewModelCImpl.registerViewModel(DaggerQuestApplication_HiltComponents_SingletonC.java:755)
        at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$ViewModelCImpl.access$3000(DaggerQuestApplication_HiltComponents_SingletonC.java:700)
        at org.smartregister.fhircore.quest.DaggerQuestApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerQuestApplication_HiltComponents_SingletonC.java:816)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:100)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:109)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at org.smartregister.fhircore.engine.ui.register.BaseRegisterActivity.getRegisterViewModel(BaseRegisterActivity.kt:105)
        at org.smartregister.fhircore.engine.ui.register.BaseRegisterActivity.runSync(BaseRegisterActivity.kt:430)
        at org.smartregister.fhircore.engine.sync.SyncBroadcaster.registerSyncInitiator(SyncHandlers.kt:56)
        at org.smartregister.fhircore.engine.ui.register.BaseRegisterActivity.onCreate(BaseRegisterActivity.kt:129)
        at org.smartregister.fhircore.quest.ui.patient.register.PatientRegisterActivity.onCreate(PatientRegisterActivity.kt:40)
        at android.app.Activity.performCreate(Activity.java:6974)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2904)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3016) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1716) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:232) 
        at android.app.ActivityThread.main(ActivityThread.java:6806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by FikriMilano** [comment]
I think this crash is related to the recent CQL PR that got merged. Tried to revert and it works.
Could you have a look on this @maimoonak?

**Comment by f-odhiambo** [comment]
Out of memory
```
2022-01-25 15:18:24.455 24527-24527/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 24527
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2794020 bytes
        at android.app.ActivityClient.finishActivity(ActivityClient.java:156)
        at android.app.Activity.finish(Activity.java:6465)
        at android.app.Activity.finish(Activity.java:6499)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity.finishActivity(QuestionnaireActivity.kt:300)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity.postSaveSuccessful(QuestionnaireActivity.kt:289)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity.handleQuestionnaireSubmit$lambda-4(QuestionnaireActivity.kt:267)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity.$r8$lambda$Q3ZvH3-oznfR02Y6M-FSEGTDJaU(Unknown Source:0)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity$$ExternalSyntheticLambda0.onChanged(Unknown Source:6)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.TransactionTooLargeException: data parcel size 2794020 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:571)
        at android.app.IActivityClientController$Stub$Proxy.finishActivity(IActivityClientController.java:1496)
        at android.app.ActivityClient.finishActivity(ActivityClient.java:153)
        at android.app.Activity.finish(Activity.java:6465) 
        at android.app.Activity.finish(Activity.java:6499) 
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity.finishActivity(QuestionnaireActivity.kt:300) 
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity.postSaveSuccessful(QuestionnaireActivity.kt:289) 
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity.handleQuestionnaireSubmit$lambda-4(QuestionnaireActivity.kt:267) 
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity.$r8$lambda$Q3ZvH3-oznfR02Y6M-FSEGTDJaU(Unknown Source:0) 
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity$$ExternalSyntheticLambda0.onChanged(Unknown Source:6) 
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133) 
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151) 
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309) 
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7839) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```
CC @maimoonak @FikriMilano

**Comment by FikriMilano** [comment]
Noted @f-odhiambo @maimoonak

**Comment by FikriMilano** [comment]
I managed to fix this by running the CQL in parallel and move it's process to background thread.
It takes ~30 seconds to process after submitting, first time submitting might take up to 1 minute.
The process is heavy because of the image and CQL.
@f-odhiambo @maimoonak

**Comment by maimoonak** [comment]
@FikriMilano But it would still keep user blocked or on progress unless cql is also finished... If not can we do so, i.e. do not let user finish activity until everything is done.. otherwise app would show inaccurate data.

**Comment by FikriMilano** [comment]
@maimoonak yeah I did exactly that, the activity won't finish until the everything is done.
